// Code generated by MockGen. DO NOT EDIT.
// Source: ./infrastructures/caching/types/cache.go
//
// Generated by this command:
//
//	mockgen -source=./infrastructures/caching/types/cache.go -package=mocks -destination=internal/mocks/mock_infrastructures_caching_types_cache.go
//

// Package mocks is a generated GoMock package.
package mocks
