// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/adapters/repositories/types/access_permission.go
//
// Generated by this command:
//
//	mockgen -source=./internal/adapters/repositories/types/access_permission.go -package=mocks -destination=mocks/mock_access_permission.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/lifenetwork-ai/iam-service/internal/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockAccessPermissionRepository is a mock of AccessPermissionRepository interface.
type MockAccessPermissionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAccessPermissionRepositoryMockRecorder
	isgomock struct{}
}

// MockAccessPermissionRepositoryMockRecorder is the mock recorder for MockAccessPermissionRepository.
type MockAccessPermissionRepositoryMockRecorder struct {
	mock *MockAccessPermissionRepository
}

// NewMockAccessPermissionRepository creates a new mock instance.
func NewMockAccessPermissionRepository(ctrl *gomock.Controller) *MockAccessPermissionRepository {
	mock := &MockAccessPermissionRepository{ctrl: ctrl}
	mock.recorder = &MockAccessPermissionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccessPermissionRepository) EXPECT() *MockAccessPermissionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAccessPermissionRepository) Create(ctx context.Context, entity domain.AccessPermission) (*domain.AccessPermission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, entity)
	ret0, _ := ret[0].(*domain.AccessPermission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAccessPermissionRepositoryMockRecorder) Create(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAccessPermissionRepository)(nil).Create), ctx, entity)
}

// Delete mocks base method.
func (m *MockAccessPermissionRepository) Delete(ctx context.Context, id string) (*domain.AccessPermission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(*domain.AccessPermission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockAccessPermissionRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAccessPermissionRepository)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockAccessPermissionRepository) Get(ctx context.Context, limit, offset int, keyword string) ([]domain.AccessPermission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, limit, offset, keyword)
	ret0, _ := ret[0].([]domain.AccessPermission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAccessPermissionRepositoryMockRecorder) Get(ctx, limit, offset, keyword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAccessPermissionRepository)(nil).Get), ctx, limit, offset, keyword)
}

// GetByCode mocks base method.
func (m *MockAccessPermissionRepository) GetByCode(ctx context.Context, code string) (*domain.AccessPermission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", ctx, code)
	ret0, _ := ret[0].(*domain.AccessPermission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MockAccessPermissionRepositoryMockRecorder) GetByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MockAccessPermissionRepository)(nil).GetByCode), ctx, code)
}

// GetByID mocks base method.
func (m *MockAccessPermissionRepository) GetByID(ctx context.Context, id string) (*domain.AccessPermission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.AccessPermission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAccessPermissionRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAccessPermissionRepository)(nil).GetByID), ctx, id)
}

// SoftDelete mocks base method.
func (m *MockAccessPermissionRepository) SoftDelete(ctx context.Context, id string) (*domain.AccessPermission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(*domain.AccessPermission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockAccessPermissionRepositoryMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockAccessPermissionRepository)(nil).SoftDelete), ctx, id)
}

// Update mocks base method.
func (m *MockAccessPermissionRepository) Update(ctx context.Context, entity domain.AccessPermission) (*domain.AccessPermission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, entity)
	ret0, _ := ret[0].(*domain.AccessPermission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockAccessPermissionRepositoryMockRecorder) Update(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAccessPermissionRepository)(nil).Update), ctx, entity)
}
