// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/adapters/repositories/types/identity_organization.go
//
// Generated by this command:
//
//	mockgen -source=./internal/adapters/repositories/types/identity_organization.go -package=mocks -destination=internal/mocks/mock_internal_adapters_repositories_types_identity_organization.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/lifenetwork-ai/iam-service/internal/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockIdentityOrganizationRepository is a mock of IdentityOrganizationRepository interface.
type MockIdentityOrganizationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityOrganizationRepositoryMockRecorder
	isgomock struct{}
}

// MockIdentityOrganizationRepositoryMockRecorder is the mock recorder for MockIdentityOrganizationRepository.
type MockIdentityOrganizationRepositoryMockRecorder struct {
	mock *MockIdentityOrganizationRepository
}

// NewMockIdentityOrganizationRepository creates a new mock instance.
func NewMockIdentityOrganizationRepository(ctrl *gomock.Controller) *MockIdentityOrganizationRepository {
	mock := &MockIdentityOrganizationRepository{ctrl: ctrl}
	mock.recorder = &MockIdentityOrganizationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityOrganizationRepository) EXPECT() *MockIdentityOrganizationRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIdentityOrganizationRepository) Create(ctx context.Context, entity domain.IdentityOrganization) (*domain.IdentityOrganization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, entity)
	ret0, _ := ret[0].(*domain.IdentityOrganization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIdentityOrganizationRepositoryMockRecorder) Create(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIdentityOrganizationRepository)(nil).Create), ctx, entity)
}

// Delete mocks base method.
func (m *MockIdentityOrganizationRepository) Delete(ctx context.Context, id string) (*domain.IdentityOrganization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(*domain.IdentityOrganization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockIdentityOrganizationRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIdentityOrganizationRepository)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockIdentityOrganizationRepository) Get(ctx context.Context, limit, offset int, keyword string) ([]domain.IdentityOrganization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, limit, offset, keyword)
	ret0, _ := ret[0].([]domain.IdentityOrganization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIdentityOrganizationRepositoryMockRecorder) Get(ctx, limit, offset, keyword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIdentityOrganizationRepository)(nil).Get), ctx, limit, offset, keyword)
}

// GetByCode mocks base method.
func (m *MockIdentityOrganizationRepository) GetByCode(ctx context.Context, code string) (*domain.IdentityOrganization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", ctx, code)
	ret0, _ := ret[0].(*domain.IdentityOrganization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MockIdentityOrganizationRepositoryMockRecorder) GetByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MockIdentityOrganizationRepository)(nil).GetByCode), ctx, code)
}

// GetByID mocks base method.
func (m *MockIdentityOrganizationRepository) GetByID(ctx context.Context, id string) (*domain.IdentityOrganization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.IdentityOrganization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIdentityOrganizationRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIdentityOrganizationRepository)(nil).GetByID), ctx, id)
}

// SoftDelete mocks base method.
func (m *MockIdentityOrganizationRepository) SoftDelete(ctx context.Context, id string) (*domain.IdentityOrganization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(*domain.IdentityOrganization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockIdentityOrganizationRepositoryMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockIdentityOrganizationRepository)(nil).SoftDelete), ctx, id)
}

// Update mocks base method.
func (m *MockIdentityOrganizationRepository) Update(ctx context.Context, entity domain.IdentityOrganization) (*domain.IdentityOrganization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, entity)
	ret0, _ := ret[0].(*domain.IdentityOrganization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockIdentityOrganizationRepositoryMockRecorder) Update(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIdentityOrganizationRepository)(nil).Update), ctx, entity)
}
