// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/ucases/types/identity_organization.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/ucases/types/identity_organization.go -package=mocks -destination=internal/mocks/mock_internal_domain_ucases_types_identity_organization.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/lifenetwork-ai/iam-service/internal/delivery/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockIdentityOrganizationUseCase is a mock of IdentityOrganizationUseCase interface.
type MockIdentityOrganizationUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityOrganizationUseCaseMockRecorder
	isgomock struct{}
}

// MockIdentityOrganizationUseCaseMockRecorder is the mock recorder for MockIdentityOrganizationUseCase.
type MockIdentityOrganizationUseCaseMockRecorder struct {
	mock *MockIdentityOrganizationUseCase
}

// NewMockIdentityOrganizationUseCase creates a new mock instance.
func NewMockIdentityOrganizationUseCase(ctrl *gomock.Controller) *MockIdentityOrganizationUseCase {
	mock := &MockIdentityOrganizationUseCase{ctrl: ctrl}
	mock.recorder = &MockIdentityOrganizationUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityOrganizationUseCase) EXPECT() *MockIdentityOrganizationUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIdentityOrganizationUseCase) Create(ctx context.Context, payload dto.CreateIdentityOrganizationPayloadDTO) (*dto.IdentityOrganizationDTO, *dto.ErrorDTOResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, payload)
	ret0, _ := ret[0].(*dto.IdentityOrganizationDTO)
	ret1, _ := ret[1].(*dto.ErrorDTOResponse)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIdentityOrganizationUseCaseMockRecorder) Create(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIdentityOrganizationUseCase)(nil).Create), ctx, payload)
}

// Delete mocks base method.
func (m *MockIdentityOrganizationUseCase) Delete(ctx context.Context, id string) (*dto.IdentityOrganizationDTO, *dto.ErrorDTOResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(*dto.IdentityOrganizationDTO)
	ret1, _ := ret[1].(*dto.ErrorDTOResponse)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockIdentityOrganizationUseCaseMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIdentityOrganizationUseCase)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockIdentityOrganizationUseCase) GetByID(ctx context.Context, id string) (*dto.IdentityOrganizationDTO, *dto.ErrorDTOResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*dto.IdentityOrganizationDTO)
	ret1, _ := ret[1].(*dto.ErrorDTOResponse)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIdentityOrganizationUseCaseMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIdentityOrganizationUseCase)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockIdentityOrganizationUseCase) List(ctx context.Context, page, size int, keyword string) (*dto.PaginationDTOResponse, *dto.ErrorDTOResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, page, size, keyword)
	ret0, _ := ret[0].(*dto.PaginationDTOResponse)
	ret1, _ := ret[1].(*dto.ErrorDTOResponse)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIdentityOrganizationUseCaseMockRecorder) List(ctx, page, size, keyword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIdentityOrganizationUseCase)(nil).List), ctx, page, size, keyword)
}

// Update mocks base method.
func (m *MockIdentityOrganizationUseCase) Update(ctx context.Context, id string, payload dto.UpdateIdentityOrganizationPayloadDTO) (*dto.IdentityOrganizationDTO, *dto.ErrorDTOResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, payload)
	ret0, _ := ret[0].(*dto.IdentityOrganizationDTO)
	ret1, _ := ret[1].(*dto.ErrorDTOResponse)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockIdentityOrganizationUseCaseMockRecorder) Update(ctx, id, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIdentityOrganizationUseCase)(nil).Update), ctx, id, payload)
}
