// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/adapters/repositories/types/identity_role.go
//
// Generated by this command:
//
//	mockgen -source=./internal/adapters/repositories/types/identity_role.go -package=mock_types -destination=mocks/adapters/repositories/types/mock_identity_role.go
//

// Package mock_types is a generated GoMock package.
package mock_types

import (
	context "context"
	reflect "reflect"

	domain "github.com/lifenetwork-ai/iam-service/internal/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockIdentityRoleRepository is a mock of IdentityRoleRepository interface.
type MockIdentityRoleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityRoleRepositoryMockRecorder
	isgomock struct{}
}

// MockIdentityRoleRepositoryMockRecorder is the mock recorder for MockIdentityRoleRepository.
type MockIdentityRoleRepositoryMockRecorder struct {
	mock *MockIdentityRoleRepository
}

// NewMockIdentityRoleRepository creates a new mock instance.
func NewMockIdentityRoleRepository(ctrl *gomock.Controller) *MockIdentityRoleRepository {
	mock := &MockIdentityRoleRepository{ctrl: ctrl}
	mock.recorder = &MockIdentityRoleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityRoleRepository) EXPECT() *MockIdentityRoleRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIdentityRoleRepository) Create(ctx context.Context, entity domain.IdentityRole) (*domain.IdentityRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, entity)
	ret0, _ := ret[0].(*domain.IdentityRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIdentityRoleRepositoryMockRecorder) Create(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIdentityRoleRepository)(nil).Create), ctx, entity)
}

// Delete mocks base method.
func (m *MockIdentityRoleRepository) Delete(ctx context.Context, id string) (*domain.IdentityRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(*domain.IdentityRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockIdentityRoleRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIdentityRoleRepository)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockIdentityRoleRepository) Get(ctx context.Context, limit, offset int, keyword string) ([]domain.IdentityRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, limit, offset, keyword)
	ret0, _ := ret[0].([]domain.IdentityRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIdentityRoleRepositoryMockRecorder) Get(ctx, limit, offset, keyword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIdentityRoleRepository)(nil).Get), ctx, limit, offset, keyword)
}

// GetByCode mocks base method.
func (m *MockIdentityRoleRepository) GetByCode(ctx context.Context, code string) (*domain.IdentityRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", ctx, code)
	ret0, _ := ret[0].(*domain.IdentityRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MockIdentityRoleRepositoryMockRecorder) GetByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MockIdentityRoleRepository)(nil).GetByCode), ctx, code)
}

// GetByID mocks base method.
func (m *MockIdentityRoleRepository) GetByID(ctx context.Context, id string) (*domain.IdentityRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.IdentityRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIdentityRoleRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIdentityRoleRepository)(nil).GetByID), ctx, id)
}

// SoftDelete mocks base method.
func (m *MockIdentityRoleRepository) SoftDelete(ctx context.Context, id string) (*domain.IdentityRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(*domain.IdentityRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockIdentityRoleRepositoryMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockIdentityRoleRepository)(nil).SoftDelete), ctx, id)
}

// Update mocks base method.
func (m *MockIdentityRoleRepository) Update(ctx context.Context, entity domain.IdentityRole) (*domain.IdentityRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, entity)
	ret0, _ := ret[0].(*domain.IdentityRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockIdentityRoleRepositoryMockRecorder) Update(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIdentityRoleRepository)(nil).Update), ctx, entity)
}
