// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/adapters/repositories/types/identity_service.go
//
// Generated by this command:
//
//	mockgen -source=./internal/adapters/repositories/types/identity_service.go -package=mock_types -destination=mocks/adapters/repositories/types/mock_identity_service.go
//

// Package mock_types is a generated GoMock package.
package mock_types

import (
	context "context"
	reflect "reflect"

	domain "github.com/lifenetwork-ai/iam-service/internal/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockIdentityServiceRepository is a mock of IdentityServiceRepository interface.
type MockIdentityServiceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityServiceRepositoryMockRecorder
	isgomock struct{}
}

// MockIdentityServiceRepositoryMockRecorder is the mock recorder for MockIdentityServiceRepository.
type MockIdentityServiceRepositoryMockRecorder struct {
	mock *MockIdentityServiceRepository
}

// NewMockIdentityServiceRepository creates a new mock instance.
func NewMockIdentityServiceRepository(ctrl *gomock.Controller) *MockIdentityServiceRepository {
	mock := &MockIdentityServiceRepository{ctrl: ctrl}
	mock.recorder = &MockIdentityServiceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityServiceRepository) EXPECT() *MockIdentityServiceRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIdentityServiceRepository) Create(ctx context.Context, entity domain.IdentityService) (*domain.IdentityService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, entity)
	ret0, _ := ret[0].(*domain.IdentityService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIdentityServiceRepositoryMockRecorder) Create(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIdentityServiceRepository)(nil).Create), ctx, entity)
}

// Delete mocks base method.
func (m *MockIdentityServiceRepository) Delete(ctx context.Context, id string) (*domain.IdentityService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(*domain.IdentityService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockIdentityServiceRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIdentityServiceRepository)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockIdentityServiceRepository) Get(ctx context.Context, limit, offset int, keyword string) ([]domain.IdentityService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, limit, offset, keyword)
	ret0, _ := ret[0].([]domain.IdentityService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIdentityServiceRepositoryMockRecorder) Get(ctx, limit, offset, keyword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIdentityServiceRepository)(nil).Get), ctx, limit, offset, keyword)
}

// GetByCode mocks base method.
func (m *MockIdentityServiceRepository) GetByCode(ctx context.Context, code string) (*domain.IdentityService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", ctx, code)
	ret0, _ := ret[0].(*domain.IdentityService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MockIdentityServiceRepositoryMockRecorder) GetByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MockIdentityServiceRepository)(nil).GetByCode), ctx, code)
}

// GetByID mocks base method.
func (m *MockIdentityServiceRepository) GetByID(ctx context.Context, id string) (*domain.IdentityService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.IdentityService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIdentityServiceRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIdentityServiceRepository)(nil).GetByID), ctx, id)
}

// SoftDelete mocks base method.
func (m *MockIdentityServiceRepository) SoftDelete(ctx context.Context, id string) (*domain.IdentityService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(*domain.IdentityService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockIdentityServiceRepositoryMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockIdentityServiceRepository)(nil).SoftDelete), ctx, id)
}

// Update mocks base method.
func (m *MockIdentityServiceRepository) Update(ctx context.Context, entity domain.IdentityService) (*domain.IdentityService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, entity)
	ret0, _ := ret[0].(*domain.IdentityService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockIdentityServiceRepositoryMockRecorder) Update(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIdentityServiceRepository)(nil).Update), ctx, entity)
}
