// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/ucases/services/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/ucases/services/interfaces.go -package=mock_services -destination=mocks/domain/ucases/services/mock_interfaces.go
//

// Package mock_services is a generated GoMock package.
package mock_services

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	constants "github.com/lifenetwork-ai/iam-service/constants"
	errors "github.com/lifenetwork-ai/iam-service/internal/domain/ucases/errors"
	types "github.com/lifenetwork-ai/iam-service/internal/domain/ucases/types"
	client "github.com/ory/kratos-client-go"
	gomock "go.uber.org/mock/gomock"
)

// MockKratosService is a mock of KratosService interface.
type MockKratosService struct {
	ctrl     *gomock.Controller
	recorder *MockKratosServiceMockRecorder
	isgomock struct{}
}

// MockKratosServiceMockRecorder is the mock recorder for MockKratosService.
type MockKratosServiceMockRecorder struct {
	mock *MockKratosService
}

// NewMockKratosService creates a new mock instance.
func NewMockKratosService(ctrl *gomock.Controller) *MockKratosService {
	mock := &MockKratosService{ctrl: ctrl}
	mock.recorder = &MockKratosServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKratosService) EXPECT() *MockKratosServiceMockRecorder {
	return m.recorder
}

// CreateIdentityAdmin mocks base method.
func (m *MockKratosService) CreateIdentityAdmin(ctx context.Context, tenantID uuid.UUID, traits map[string]any) (*client.Identity, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIdentityAdmin", ctx, tenantID, traits)
	ret0, _ := ret[0].(*client.Identity)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateIdentityAdmin indicates an expected call of CreateIdentityAdmin.
func (mr *MockKratosServiceMockRecorder) CreateIdentityAdmin(ctx, tenantID, traits any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIdentityAdmin", reflect.TypeOf((*MockKratosService)(nil).CreateIdentityAdmin), ctx, tenantID, traits)
}

// DeleteIdentifierAdmin mocks base method.
func (m *MockKratosService) DeleteIdentifierAdmin(ctx context.Context, tenantID, identityID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIdentifierAdmin", ctx, tenantID, identityID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIdentifierAdmin indicates an expected call of DeleteIdentifierAdmin.
func (mr *MockKratosServiceMockRecorder) DeleteIdentifierAdmin(ctx, tenantID, identityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIdentifierAdmin", reflect.TypeOf((*MockKratosService)(nil).DeleteIdentifierAdmin), ctx, tenantID, identityID)
}

// GetIdentity mocks base method.
func (m *MockKratosService) GetIdentity(ctx context.Context, tenantID, identityID uuid.UUID) (*client.Identity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIdentity", ctx, tenantID, identityID)
	ret0, _ := ret[0].(*client.Identity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIdentity indicates an expected call of GetIdentity.
func (mr *MockKratosServiceMockRecorder) GetIdentity(ctx, tenantID, identityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIdentity", reflect.TypeOf((*MockKratosService)(nil).GetIdentity), ctx, tenantID, identityID)
}

// GetLoginFlow mocks base method.
func (m *MockKratosService) GetLoginFlow(ctx context.Context, tenantID uuid.UUID, flowID string) (*client.LoginFlow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoginFlow", ctx, tenantID, flowID)
	ret0, _ := ret[0].(*client.LoginFlow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLoginFlow indicates an expected call of GetLoginFlow.
func (mr *MockKratosServiceMockRecorder) GetLoginFlow(ctx, tenantID, flowID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoginFlow", reflect.TypeOf((*MockKratosService)(nil).GetLoginFlow), ctx, tenantID, flowID)
}

// GetRegistrationFlow mocks base method.
func (m *MockKratosService) GetRegistrationFlow(ctx context.Context, tenantID uuid.UUID, flowID string) (*client.RegistrationFlow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegistrationFlow", ctx, tenantID, flowID)
	ret0, _ := ret[0].(*client.RegistrationFlow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegistrationFlow indicates an expected call of GetRegistrationFlow.
func (mr *MockKratosServiceMockRecorder) GetRegistrationFlow(ctx, tenantID, flowID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegistrationFlow", reflect.TypeOf((*MockKratosService)(nil).GetRegistrationFlow), ctx, tenantID, flowID)
}

// GetSession mocks base method.
func (m *MockKratosService) GetSession(ctx context.Context, tenantID uuid.UUID, sessionToken string) (*client.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", ctx, tenantID, sessionToken)
	ret0, _ := ret[0].(*client.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockKratosServiceMockRecorder) GetSession(ctx, tenantID, sessionToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockKratosService)(nil).GetSession), ctx, tenantID, sessionToken)
}

// GetSettingsFlow mocks base method.
func (m *MockKratosService) GetSettingsFlow(ctx context.Context, tenantID uuid.UUID, flowID, sessionToken string) (*client.SettingsFlow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSettingsFlow", ctx, tenantID, flowID, sessionToken)
	ret0, _ := ret[0].(*client.SettingsFlow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSettingsFlow indicates an expected call of GetSettingsFlow.
func (mr *MockKratosServiceMockRecorder) GetSettingsFlow(ctx, tenantID, flowID, sessionToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSettingsFlow", reflect.TypeOf((*MockKratosService)(nil).GetSettingsFlow), ctx, tenantID, flowID, sessionToken)
}

// GetVerificationFlow mocks base method.
func (m *MockKratosService) GetVerificationFlow(ctx context.Context, tenantID uuid.UUID, flowID string) (*client.VerificationFlow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVerificationFlow", ctx, tenantID, flowID)
	ret0, _ := ret[0].(*client.VerificationFlow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVerificationFlow indicates an expected call of GetVerificationFlow.
func (mr *MockKratosServiceMockRecorder) GetVerificationFlow(ctx, tenantID, flowID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVerificationFlow", reflect.TypeOf((*MockKratosService)(nil).GetVerificationFlow), ctx, tenantID, flowID)
}

// InitializeLoginFlow mocks base method.
func (m *MockKratosService) InitializeLoginFlow(ctx context.Context, tenantID uuid.UUID) (*client.LoginFlow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitializeLoginFlow", ctx, tenantID)
	ret0, _ := ret[0].(*client.LoginFlow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitializeLoginFlow indicates an expected call of InitializeLoginFlow.
func (mr *MockKratosServiceMockRecorder) InitializeLoginFlow(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitializeLoginFlow", reflect.TypeOf((*MockKratosService)(nil).InitializeLoginFlow), ctx, tenantID)
}

// InitializeRegistrationFlow mocks base method.
func (m *MockKratosService) InitializeRegistrationFlow(ctx context.Context, tenantID uuid.UUID) (*client.RegistrationFlow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitializeRegistrationFlow", ctx, tenantID)
	ret0, _ := ret[0].(*client.RegistrationFlow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitializeRegistrationFlow indicates an expected call of InitializeRegistrationFlow.
func (mr *MockKratosServiceMockRecorder) InitializeRegistrationFlow(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitializeRegistrationFlow", reflect.TypeOf((*MockKratosService)(nil).InitializeRegistrationFlow), ctx, tenantID)
}

// InitializeSettingsFlow mocks base method.
func (m *MockKratosService) InitializeSettingsFlow(ctx context.Context, tenantID uuid.UUID, sessionToken string) (*client.SettingsFlow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitializeSettingsFlow", ctx, tenantID, sessionToken)
	ret0, _ := ret[0].(*client.SettingsFlow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitializeSettingsFlow indicates an expected call of InitializeSettingsFlow.
func (mr *MockKratosServiceMockRecorder) InitializeSettingsFlow(ctx, tenantID, sessionToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitializeSettingsFlow", reflect.TypeOf((*MockKratosService)(nil).InitializeSettingsFlow), ctx, tenantID, sessionToken)
}

// InitializeVerificationFlow mocks base method.
func (m *MockKratosService) InitializeVerificationFlow(ctx context.Context, tenantID uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitializeVerificationFlow", ctx, tenantID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitializeVerificationFlow indicates an expected call of InitializeVerificationFlow.
func (mr *MockKratosServiceMockRecorder) InitializeVerificationFlow(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitializeVerificationFlow", reflect.TypeOf((*MockKratosService)(nil).InitializeVerificationFlow), ctx, tenantID)
}

// Logout mocks base method.
func (m *MockKratosService) Logout(ctx context.Context, tenantID uuid.UUID, sessionToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, tenantID, sessionToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockKratosServiceMockRecorder) Logout(ctx, tenantID, sessionToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockKratosService)(nil).Logout), ctx, tenantID, sessionToken)
}

// RevokeSession mocks base method.
func (m *MockKratosService) RevokeSession(ctx context.Context, tenantID uuid.UUID, sessionToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeSession", ctx, tenantID, sessionToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeSession indicates an expected call of RevokeSession.
func (mr *MockKratosServiceMockRecorder) RevokeSession(ctx, tenantID, sessionToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeSession", reflect.TypeOf((*MockKratosService)(nil).RevokeSession), ctx, tenantID, sessionToken)
}

// SubmitLoginFlow mocks base method.
func (m *MockKratosService) SubmitLoginFlow(ctx context.Context, tenantID uuid.UUID, flow *client.LoginFlow, method string, identifier, password, code *string) (*client.SuccessfulNativeLogin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitLoginFlow", ctx, tenantID, flow, method, identifier, password, code)
	ret0, _ := ret[0].(*client.SuccessfulNativeLogin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitLoginFlow indicates an expected call of SubmitLoginFlow.
func (mr *MockKratosServiceMockRecorder) SubmitLoginFlow(ctx, tenantID, flow, method, identifier, password, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitLoginFlow", reflect.TypeOf((*MockKratosService)(nil).SubmitLoginFlow), ctx, tenantID, flow, method, identifier, password, code)
}

// SubmitRegistrationFlow mocks base method.
func (m *MockKratosService) SubmitRegistrationFlow(ctx context.Context, tenantID uuid.UUID, flow *client.RegistrationFlow, method string, traits map[string]any) (*client.SuccessfulNativeRegistration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitRegistrationFlow", ctx, tenantID, flow, method, traits)
	ret0, _ := ret[0].(*client.SuccessfulNativeRegistration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitRegistrationFlow indicates an expected call of SubmitRegistrationFlow.
func (mr *MockKratosServiceMockRecorder) SubmitRegistrationFlow(ctx, tenantID, flow, method, traits any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitRegistrationFlow", reflect.TypeOf((*MockKratosService)(nil).SubmitRegistrationFlow), ctx, tenantID, flow, method, traits)
}

// SubmitRegistrationFlowWithCode mocks base method.
func (m *MockKratosService) SubmitRegistrationFlowWithCode(ctx context.Context, tenantID uuid.UUID, flow *client.RegistrationFlow, code string) (*client.SuccessfulNativeRegistration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitRegistrationFlowWithCode", ctx, tenantID, flow, code)
	ret0, _ := ret[0].(*client.SuccessfulNativeRegistration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitRegistrationFlowWithCode indicates an expected call of SubmitRegistrationFlowWithCode.
func (mr *MockKratosServiceMockRecorder) SubmitRegistrationFlowWithCode(ctx, tenantID, flow, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitRegistrationFlowWithCode", reflect.TypeOf((*MockKratosService)(nil).SubmitRegistrationFlowWithCode), ctx, tenantID, flow, code)
}

// SubmitSettingsFlow mocks base method.
func (m *MockKratosService) SubmitSettingsFlow(ctx context.Context, tenantID uuid.UUID, flow *client.SettingsFlow, sessionToken, method string, traits map[string]any) (*client.SettingsFlow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitSettingsFlow", ctx, tenantID, flow, sessionToken, method, traits)
	ret0, _ := ret[0].(*client.SettingsFlow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitSettingsFlow indicates an expected call of SubmitSettingsFlow.
func (mr *MockKratosServiceMockRecorder) SubmitSettingsFlow(ctx, tenantID, flow, sessionToken, method, traits any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitSettingsFlow", reflect.TypeOf((*MockKratosService)(nil).SubmitSettingsFlow), ctx, tenantID, flow, sessionToken, method, traits)
}

// SubmitVerificationFlow mocks base method.
func (m *MockKratosService) SubmitVerificationFlow(ctx context.Context, tenantID uuid.UUID, flowID string, identifier *string, identifierType constants.IdentifierType, code *string) (*client.VerificationFlow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitVerificationFlow", ctx, tenantID, flowID, identifier, identifierType, code)
	ret0, _ := ret[0].(*client.VerificationFlow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitVerificationFlow indicates an expected call of SubmitVerificationFlow.
func (mr *MockKratosServiceMockRecorder) SubmitVerificationFlow(ctx, tenantID, flowID, identifier, identifierType, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitVerificationFlow", reflect.TypeOf((*MockKratosService)(nil).SubmitVerificationFlow), ctx, tenantID, flowID, identifier, identifierType, code)
}

// UpdateIdentifierTraitAdmin mocks base method.
func (m *MockKratosService) UpdateIdentifierTraitAdmin(ctx context.Context, tenantID, identityID uuid.UUID, traits map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIdentifierTraitAdmin", ctx, tenantID, identityID, traits)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateIdentifierTraitAdmin indicates an expected call of UpdateIdentifierTraitAdmin.
func (mr *MockKratosServiceMockRecorder) UpdateIdentifierTraitAdmin(ctx, tenantID, identityID, traits any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIdentifierTraitAdmin", reflect.TypeOf((*MockKratosService)(nil).UpdateIdentifierTraitAdmin), ctx, tenantID, identityID, traits)
}

// UpdateLangAdmin mocks base method.
func (m *MockKratosService) UpdateLangAdmin(ctx context.Context, tenantID, identityID uuid.UUID, newLang string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLangAdmin", ctx, tenantID, identityID, newLang)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLangAdmin indicates an expected call of UpdateLangAdmin.
func (mr *MockKratosServiceMockRecorder) UpdateLangAdmin(ctx, tenantID, identityID, newLang any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLangAdmin", reflect.TypeOf((*MockKratosService)(nil).UpdateLangAdmin), ctx, tenantID, identityID, newLang)
}

// WhoAmI mocks base method.
func (m *MockKratosService) WhoAmI(ctx context.Context, tenantID uuid.UUID, sessionToken string) (*client.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WhoAmI", ctx, tenantID, sessionToken)
	ret0, _ := ret[0].(*client.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WhoAmI indicates an expected call of WhoAmI.
func (mr *MockKratosServiceMockRecorder) WhoAmI(ctx, tenantID, sessionToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WhoAmI", reflect.TypeOf((*MockKratosService)(nil).WhoAmI), ctx, tenantID, sessionToken)
}

// MockKetoService is a mock of KetoService interface.
type MockKetoService struct {
	ctrl     *gomock.Controller
	recorder *MockKetoServiceMockRecorder
	isgomock struct{}
}

// MockKetoServiceMockRecorder is the mock recorder for MockKetoService.
type MockKetoServiceMockRecorder struct {
	mock *MockKetoService
}

// NewMockKetoService creates a new mock instance.
func NewMockKetoService(ctrl *gomock.Controller) *MockKetoService {
	mock := &MockKetoService{ctrl: ctrl}
	mock.recorder = &MockKetoServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKetoService) EXPECT() *MockKetoServiceMockRecorder {
	return m.recorder
}

// CheckPermission mocks base method.
func (m *MockKetoService) CheckPermission(ctx context.Context, request types.CheckPermissionRequest) (bool, *errors.DomainError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPermission", ctx, request)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*errors.DomainError)
	return ret0, ret1
}

// CheckPermission indicates an expected call of CheckPermission.
func (mr *MockKetoServiceMockRecorder) CheckPermission(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPermission", reflect.TypeOf((*MockKetoService)(nil).CheckPermission), ctx, request)
}

// CreateRelationTuple mocks base method.
func (m *MockKetoService) CreateRelationTuple(ctx context.Context, request types.CreateRelationTupleRequest) *errors.DomainError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRelationTuple", ctx, request)
	ret0, _ := ret[0].(*errors.DomainError)
	return ret0
}

// CreateRelationTuple indicates an expected call of CreateRelationTuple.
func (mr *MockKetoServiceMockRecorder) CreateRelationTuple(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRelationTuple", reflect.TypeOf((*MockKetoService)(nil).CreateRelationTuple), ctx, request)
}

// MockSMSProvider is a mock of SMSProvider interface.
type MockSMSProvider struct {
	ctrl     *gomock.Controller
	recorder *MockSMSProviderMockRecorder
	isgomock struct{}
}

// MockSMSProviderMockRecorder is the mock recorder for MockSMSProvider.
type MockSMSProviderMockRecorder struct {
	mock *MockSMSProvider
}

// NewMockSMSProvider creates a new mock instance.
func NewMockSMSProvider(ctrl *gomock.Controller) *MockSMSProvider {
	mock := &MockSMSProvider{ctrl: ctrl}
	mock.recorder = &MockSMSProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSMSProvider) EXPECT() *MockSMSProviderMockRecorder {
	return m.recorder
}

// SendOTP mocks base method.
func (m *MockSMSProvider) SendOTP(ctx context.Context, tenantName, receiver, channel, message string, ttl time.Duration, lang string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendOTP", ctx, tenantName, receiver, channel, message, ttl, lang)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendOTP indicates an expected call of SendOTP.
func (mr *MockSMSProviderMockRecorder) SendOTP(ctx, tenantName, receiver, channel, message, ttl, lang any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendOTP", reflect.TypeOf((*MockSMSProvider)(nil).SendOTP), ctx, tenantName, receiver, channel, message, ttl, lang)
}
