// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/ucases/types/identity_role.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/ucases/types/identity_role.go -package=mock_types -destination=mocks/domain/ucases/types/mock_identity_role.go
//

// Package mock_types is a generated GoMock package.
package mock_types

import (
	context "context"
	reflect "reflect"

	dto "github.com/lifenetwork-ai/iam-service/internal/delivery/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockIdentityRoleUseCase is a mock of IdentityRoleUseCase interface.
type MockIdentityRoleUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityRoleUseCaseMockRecorder
	isgomock struct{}
}

// MockIdentityRoleUseCaseMockRecorder is the mock recorder for MockIdentityRoleUseCase.
type MockIdentityRoleUseCaseMockRecorder struct {
	mock *MockIdentityRoleUseCase
}

// NewMockIdentityRoleUseCase creates a new mock instance.
func NewMockIdentityRoleUseCase(ctrl *gomock.Controller) *MockIdentityRoleUseCase {
	mock := &MockIdentityRoleUseCase{ctrl: ctrl}
	mock.recorder = &MockIdentityRoleUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityRoleUseCase) EXPECT() *MockIdentityRoleUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIdentityRoleUseCase) Create(ctx context.Context, payload dto.CreateIdentityRolePayloadDTO) (*dto.IdentityRoleDTO, *dto.ErrorDTOResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, payload)
	ret0, _ := ret[0].(*dto.IdentityRoleDTO)
	ret1, _ := ret[1].(*dto.ErrorDTOResponse)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIdentityRoleUseCaseMockRecorder) Create(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIdentityRoleUseCase)(nil).Create), ctx, payload)
}

// Delete mocks base method.
func (m *MockIdentityRoleUseCase) Delete(ctx context.Context, id string) (*dto.IdentityRoleDTO, *dto.ErrorDTOResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(*dto.IdentityRoleDTO)
	ret1, _ := ret[1].(*dto.ErrorDTOResponse)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockIdentityRoleUseCaseMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIdentityRoleUseCase)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockIdentityRoleUseCase) GetByID(ctx context.Context, id string) (*dto.IdentityRoleDTO, *dto.ErrorDTOResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*dto.IdentityRoleDTO)
	ret1, _ := ret[1].(*dto.ErrorDTOResponse)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIdentityRoleUseCaseMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIdentityRoleUseCase)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockIdentityRoleUseCase) List(ctx context.Context, page, size int, keyword string) (*dto.PaginationDTOResponse, *dto.ErrorDTOResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, page, size, keyword)
	ret0, _ := ret[0].(*dto.PaginationDTOResponse)
	ret1, _ := ret[1].(*dto.ErrorDTOResponse)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIdentityRoleUseCaseMockRecorder) List(ctx, page, size, keyword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIdentityRoleUseCase)(nil).List), ctx, page, size, keyword)
}

// Update mocks base method.
func (m *MockIdentityRoleUseCase) Update(ctx context.Context, id string, payload dto.UpdateIdentityRolePayloadDTO) (*dto.IdentityRoleDTO, *dto.ErrorDTOResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, payload)
	ret0, _ := ret[0].(*dto.IdentityRoleDTO)
	ret1, _ := ret[1].(*dto.ErrorDTOResponse)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockIdentityRoleUseCaseMockRecorder) Update(ctx, id, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIdentityRoleUseCase)(nil).Update), ctx, id, payload)
}
