// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/ucases/types/identity_group.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/ucases/types/identity_group.go -package=mock_types -destination=mocks/domain/ucases/types/mock_identity_group.go
//

// Package mock_types is a generated GoMock package.
package mock_types

import (
	context "context"
	reflect "reflect"

	dto "github.com/lifenetwork-ai/iam-service/internal/delivery/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockIdentityGroupUseCase is a mock of IdentityGroupUseCase interface.
type MockIdentityGroupUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityGroupUseCaseMockRecorder
	isgomock struct{}
}

// MockIdentityGroupUseCaseMockRecorder is the mock recorder for MockIdentityGroupUseCase.
type MockIdentityGroupUseCaseMockRecorder struct {
	mock *MockIdentityGroupUseCase
}

// NewMockIdentityGroupUseCase creates a new mock instance.
func NewMockIdentityGroupUseCase(ctrl *gomock.Controller) *MockIdentityGroupUseCase {
	mock := &MockIdentityGroupUseCase{ctrl: ctrl}
	mock.recorder = &MockIdentityGroupUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityGroupUseCase) EXPECT() *MockIdentityGroupUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIdentityGroupUseCase) Create(ctx context.Context, payload dto.CreateIdentityGroupPayloadDTO) (*dto.IdentityGroupDTO, *dto.ErrorDTOResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, payload)
	ret0, _ := ret[0].(*dto.IdentityGroupDTO)
	ret1, _ := ret[1].(*dto.ErrorDTOResponse)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIdentityGroupUseCaseMockRecorder) Create(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIdentityGroupUseCase)(nil).Create), ctx, payload)
}

// Delete mocks base method.
func (m *MockIdentityGroupUseCase) Delete(ctx context.Context, id string) (*dto.IdentityGroupDTO, *dto.ErrorDTOResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(*dto.IdentityGroupDTO)
	ret1, _ := ret[1].(*dto.ErrorDTOResponse)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockIdentityGroupUseCaseMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIdentityGroupUseCase)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockIdentityGroupUseCase) GetByID(ctx context.Context, id string) (*dto.IdentityGroupDTO, *dto.ErrorDTOResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*dto.IdentityGroupDTO)
	ret1, _ := ret[1].(*dto.ErrorDTOResponse)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIdentityGroupUseCaseMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIdentityGroupUseCase)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockIdentityGroupUseCase) List(ctx context.Context, page, size int, keyword string) (*dto.PaginationDTOResponse, *dto.ErrorDTOResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, page, size, keyword)
	ret0, _ := ret[0].(*dto.PaginationDTOResponse)
	ret1, _ := ret[1].(*dto.ErrorDTOResponse)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIdentityGroupUseCaseMockRecorder) List(ctx, page, size, keyword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIdentityGroupUseCase)(nil).List), ctx, page, size, keyword)
}

// Update mocks base method.
func (m *MockIdentityGroupUseCase) Update(ctx context.Context, id string, payload dto.UpdateIdentityGroupPayloadDTO) (*dto.IdentityGroupDTO, *dto.ErrorDTOResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, payload)
	ret0, _ := ret[0].(*dto.IdentityGroupDTO)
	ret1, _ := ret[1].(*dto.ErrorDTOResponse)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockIdentityGroupUseCaseMockRecorder) Update(ctx, id, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIdentityGroupUseCase)(nil).Update), ctx, id, payload)
}
