// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/ucases/types/permission.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/ucases/types/permission.go -package=mock_types -destination=mocks/domain/ucases/types/mock_permission.go
//

// Package mock_types is a generated GoMock package.
package mock_types

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPermissionRequest is a mock of PermissionRequest interface.
type MockPermissionRequest struct {
	ctrl     *gomock.Controller
	recorder *MockPermissionRequestMockRecorder
	isgomock struct{}
}

// MockPermissionRequestMockRecorder is the mock recorder for MockPermissionRequest.
type MockPermissionRequestMockRecorder struct {
	mock *MockPermissionRequest
}

// NewMockPermissionRequest creates a new mock instance.
func NewMockPermissionRequest(ctrl *gomock.Controller) *MockPermissionRequest {
	mock := &MockPermissionRequest{ctrl: ctrl}
	mock.recorder = &MockPermissionRequestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermissionRequest) EXPECT() *MockPermissionRequestMockRecorder {
	return m.recorder
}

// GetIdentifier mocks base method.
func (m *MockPermissionRequest) GetIdentifier() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIdentifier")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetIdentifier indicates an expected call of GetIdentifier.
func (mr *MockPermissionRequestMockRecorder) GetIdentifier() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIdentifier", reflect.TypeOf((*MockPermissionRequest)(nil).GetIdentifier))
}

// Validate mocks base method.
func (m *MockPermissionRequest) Validate() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate")
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockPermissionRequestMockRecorder) Validate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockPermissionRequest)(nil).Validate))
}
