// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/ucases/types/identity_service.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/ucases/types/identity_service.go -package=mock_types -destination=mocks/domain/ucases/types/mock_identity_service.go
//

// Package mock_types is a generated GoMock package.
package mock_types

import (
	context "context"
	reflect "reflect"

	dto "github.com/lifenetwork-ai/iam-service/internal/delivery/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockIdentityServiceUseCase is a mock of IdentityServiceUseCase interface.
type MockIdentityServiceUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityServiceUseCaseMockRecorder
	isgomock struct{}
}

// MockIdentityServiceUseCaseMockRecorder is the mock recorder for MockIdentityServiceUseCase.
type MockIdentityServiceUseCaseMockRecorder struct {
	mock *MockIdentityServiceUseCase
}

// NewMockIdentityServiceUseCase creates a new mock instance.
func NewMockIdentityServiceUseCase(ctrl *gomock.Controller) *MockIdentityServiceUseCase {
	mock := &MockIdentityServiceUseCase{ctrl: ctrl}
	mock.recorder = &MockIdentityServiceUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityServiceUseCase) EXPECT() *MockIdentityServiceUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIdentityServiceUseCase) Create(ctx context.Context, payload dto.CreateIdentityServicePayloadDTO) (*dto.IdentityServiceDTO, *dto.ErrorDTOResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, payload)
	ret0, _ := ret[0].(*dto.IdentityServiceDTO)
	ret1, _ := ret[1].(*dto.ErrorDTOResponse)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIdentityServiceUseCaseMockRecorder) Create(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIdentityServiceUseCase)(nil).Create), ctx, payload)
}

// Delete mocks base method.
func (m *MockIdentityServiceUseCase) Delete(ctx context.Context, id string) (*dto.IdentityServiceDTO, *dto.ErrorDTOResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(*dto.IdentityServiceDTO)
	ret1, _ := ret[1].(*dto.ErrorDTOResponse)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockIdentityServiceUseCaseMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIdentityServiceUseCase)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockIdentityServiceUseCase) GetByID(ctx context.Context, id string) (*dto.IdentityServiceDTO, *dto.ErrorDTOResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*dto.IdentityServiceDTO)
	ret1, _ := ret[1].(*dto.ErrorDTOResponse)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIdentityServiceUseCaseMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIdentityServiceUseCase)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockIdentityServiceUseCase) List(ctx context.Context, page, size int, keyword string) (*dto.PaginationDTOResponse, *dto.ErrorDTOResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, page, size, keyword)
	ret0, _ := ret[0].(*dto.PaginationDTOResponse)
	ret1, _ := ret[1].(*dto.ErrorDTOResponse)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIdentityServiceUseCaseMockRecorder) List(ctx, page, size, keyword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIdentityServiceUseCase)(nil).List), ctx, page, size, keyword)
}

// Update mocks base method.
func (m *MockIdentityServiceUseCase) Update(ctx context.Context, id string, payload dto.UpdateIdentityServicePayloadDTO) (*dto.IdentityServiceDTO, *dto.ErrorDTOResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, payload)
	ret0, _ := ret[0].(*dto.IdentityServiceDTO)
	ret1, _ := ret[1].(*dto.ErrorDTOResponse)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockIdentityServiceUseCaseMockRecorder) Update(ctx, id, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIdentityServiceUseCase)(nil).Update), ctx, id, payload)
}
