// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/ucases/types/access_policy.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/ucases/types/access_policy.go -package=mock_types -destination=mocks/domain/ucases/types/mock_access_policy.go
//

// Package mock_types is a generated GoMock package.
package mock_types

import (
	context "context"
	reflect "reflect"

	dto "github.com/lifenetwork-ai/iam-service/internal/delivery/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockAccessPolicyUseCase is a mock of AccessPolicyUseCase interface.
type MockAccessPolicyUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockAccessPolicyUseCaseMockRecorder
	isgomock struct{}
}

// MockAccessPolicyUseCaseMockRecorder is the mock recorder for MockAccessPolicyUseCase.
type MockAccessPolicyUseCaseMockRecorder struct {
	mock *MockAccessPolicyUseCase
}

// NewMockAccessPolicyUseCase creates a new mock instance.
func NewMockAccessPolicyUseCase(ctrl *gomock.Controller) *MockAccessPolicyUseCase {
	mock := &MockAccessPolicyUseCase{ctrl: ctrl}
	mock.recorder = &MockAccessPolicyUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccessPolicyUseCase) EXPECT() *MockAccessPolicyUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAccessPolicyUseCase) Create(ctx context.Context, payload dto.CreateAccessPolicyPayloadDTO) (*dto.AccessPolicyDTO, *dto.ErrorDTOResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, payload)
	ret0, _ := ret[0].(*dto.AccessPolicyDTO)
	ret1, _ := ret[1].(*dto.ErrorDTOResponse)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAccessPolicyUseCaseMockRecorder) Create(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAccessPolicyUseCase)(nil).Create), ctx, payload)
}

// Delete mocks base method.
func (m *MockAccessPolicyUseCase) Delete(ctx context.Context, id string) (*dto.AccessPolicyDTO, *dto.ErrorDTOResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(*dto.AccessPolicyDTO)
	ret1, _ := ret[1].(*dto.ErrorDTOResponse)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockAccessPolicyUseCaseMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAccessPolicyUseCase)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockAccessPolicyUseCase) GetByID(ctx context.Context, id string) (*dto.AccessPolicyDTO, *dto.ErrorDTOResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*dto.AccessPolicyDTO)
	ret1, _ := ret[1].(*dto.ErrorDTOResponse)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAccessPolicyUseCaseMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAccessPolicyUseCase)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockAccessPolicyUseCase) List(ctx context.Context, page, size int, keyword string) (*dto.PaginationDTOResponse, *dto.ErrorDTOResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, page, size, keyword)
	ret0, _ := ret[0].(*dto.PaginationDTOResponse)
	ret1, _ := ret[1].(*dto.ErrorDTOResponse)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAccessPolicyUseCaseMockRecorder) List(ctx, page, size, keyword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAccessPolicyUseCase)(nil).List), ctx, page, size, keyword)
}

// Update mocks base method.
func (m *MockAccessPolicyUseCase) Update(ctx context.Context, id string, payload dto.UpdateAccessPolicyPayloadDTO) (*dto.AccessPolicyDTO, *dto.ErrorDTOResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, payload)
	ret0, _ := ret[0].(*dto.AccessPolicyDTO)
	ret1, _ := ret[1].(*dto.ErrorDTOResponse)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockAccessPolicyUseCaseMockRecorder) Update(ctx, id, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAccessPolicyUseCase)(nil).Update), ctx, id, payload)
}
