// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/adapters/services/kratos/types/types.go
//
// Generated by this command:
//
//	mockgen -source=./internal/adapters/services/kratos/types/types.go -package=mock_types -destination=mocks/adapters/services/kratos/types/mock_types.go
//

// Package mock_types is a generated GoMock package.
package mock_types
