// Code generated by MockGen. DO NOT EDIT.
// Source: ./infrastructures/rate_limiter/types/rate_limiter.go
//
// Generated by this command:
//
//	mockgen -source=./infrastructures/rate_limiter/types/rate_limiter.go -package=mock_types -destination=mocks/infrastructures/rate_limiter/types/mock_rate_limiter.go
//

// Package mock_types is a generated GoMock package.
package mock_types

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockRateLimiter is a mock of RateLimiter interface.
type MockRateLimiter struct {
	ctrl     *gomock.Controller
	recorder *MockRateLimiterMockRecorder
	isgomock struct{}
}

// MockRateLimiterMockRecorder is the mock recorder for MockRateLimiter.
type MockRateLimiterMockRecorder struct {
	mock *MockRateLimiter
}

// NewMockRateLimiter creates a new mock instance.
func NewMockRateLimiter(ctrl *gomock.Controller) *MockRateLimiter {
	mock := &MockRateLimiter{ctrl: ctrl}
	mock.recorder = &MockRateLimiterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRateLimiter) EXPECT() *MockRateLimiterMockRecorder {
	return m.recorder
}

// IsLimited mocks base method.
func (m *MockRateLimiter) IsLimited(key string, limit int, window time.Duration) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsLimited", key, limit, window)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsLimited indicates an expected call of IsLimited.
func (mr *MockRateLimiterMockRecorder) IsLimited(key, limit, window any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsLimited", reflect.TypeOf((*MockRateLimiter)(nil).IsLimited), key, limit, window)
}

// RegisterAttempt mocks base method.
func (m *MockRateLimiter) RegisterAttempt(key string, window time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterAttempt", key, window)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterAttempt indicates an expected call of RegisterAttempt.
func (mr *MockRateLimiterMockRecorder) RegisterAttempt(key, window any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterAttempt", reflect.TypeOf((*MockRateLimiter)(nil).RegisterAttempt), key, window)
}

// ResetAttempts mocks base method.
func (m *MockRateLimiter) ResetAttempts(key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetAttempts", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetAttempts indicates an expected call of ResetAttempts.
func (mr *MockRateLimiterMockRecorder) ResetAttempts(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetAttempts", reflect.TypeOf((*MockRateLimiter)(nil).ResetAttempts), key)
}
