// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/ucases/helper.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/ucases/helper.go -package=mock_ucases -destination=mocks/domain/ucases/mock_helper.go
//

// Package mock_ucases is a generated GoMock package.
package mock_ucases
