// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/ucases/identity_user_ucase.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/ucases/identity_user_ucase.go -package=mock_ucases -destination=mocks/domain/ucases/mock_identity_user_ucase.go
//

// Package mock_ucases is a generated GoMock package.
package mock_ucases
