// Code generated by MockGen. DO NOT EDIT.
// Source: ./infrastructures/caching/types/cache.go
//
// Generated by this command:
//
//	mockgen -source=./infrastructures/caching/types/cache.go -package=mock_types -destination=mocks/infrastructures/caching/types/mock_cache.go
//

// Package mock_types is a generated GoMock package.
package mock_types
