// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/ucases/repositories/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/ucases/repositories/interfaces.go -package=mock_repositories -destination=mocks/domain/ucases/repositories/mock_interfaces.go
//

// Package mock_repositories is a generated GoMock package.
package mock_repositories

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	domain "github.com/lifenetwork-ai/iam-service/internal/domain/entities"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockAdminAccountRepository is a mock of AdminAccountRepository interface.
type MockAdminAccountRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAdminAccountRepositoryMockRecorder
	isgomock struct{}
}

// MockAdminAccountRepositoryMockRecorder is the mock recorder for MockAdminAccountRepository.
type MockAdminAccountRepositoryMockRecorder struct {
	mock *MockAdminAccountRepository
}

// NewMockAdminAccountRepository creates a new mock instance.
func NewMockAdminAccountRepository(ctrl *gomock.Controller) *MockAdminAccountRepository {
	mock := &MockAdminAccountRepository{ctrl: ctrl}
	mock.recorder = &MockAdminAccountRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminAccountRepository) EXPECT() *MockAdminAccountRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAdminAccountRepository) Create(account *domain.AdminAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", account)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAdminAccountRepositoryMockRecorder) Create(account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAdminAccountRepository)(nil).Create), account)
}

// Delete mocks base method.
func (m *MockAdminAccountRepository) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAdminAccountRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAdminAccountRepository)(nil).Delete), id)
}

// GetByID mocks base method.
func (m *MockAdminAccountRepository) GetByID(id string) (*domain.AdminAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*domain.AdminAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAdminAccountRepositoryMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAdminAccountRepository)(nil).GetByID), id)
}

// GetByUsername mocks base method.
func (m *MockAdminAccountRepository) GetByUsername(username string) (*domain.AdminAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUsername", username)
	ret0, _ := ret[0].(*domain.AdminAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUsername indicates an expected call of GetByUsername.
func (mr *MockAdminAccountRepositoryMockRecorder) GetByUsername(username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUsername", reflect.TypeOf((*MockAdminAccountRepository)(nil).GetByUsername), username)
}

// Update mocks base method.
func (m *MockAdminAccountRepository) Update(account *domain.AdminAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", account)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAdminAccountRepositoryMockRecorder) Update(account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAdminAccountRepository)(nil).Update), account)
}

// MockChallengeSessionRepository is a mock of ChallengeSessionRepository interface.
type MockChallengeSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockChallengeSessionRepositoryMockRecorder
	isgomock struct{}
}

// MockChallengeSessionRepositoryMockRecorder is the mock recorder for MockChallengeSessionRepository.
type MockChallengeSessionRepositoryMockRecorder struct {
	mock *MockChallengeSessionRepository
}

// NewMockChallengeSessionRepository creates a new mock instance.
func NewMockChallengeSessionRepository(ctrl *gomock.Controller) *MockChallengeSessionRepository {
	mock := &MockChallengeSessionRepository{ctrl: ctrl}
	mock.recorder = &MockChallengeSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChallengeSessionRepository) EXPECT() *MockChallengeSessionRepositoryMockRecorder {
	return m.recorder
}

// DeleteChallenge mocks base method.
func (m *MockChallengeSessionRepository) DeleteChallenge(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChallenge", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChallenge indicates an expected call of DeleteChallenge.
func (mr *MockChallengeSessionRepositoryMockRecorder) DeleteChallenge(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChallenge", reflect.TypeOf((*MockChallengeSessionRepository)(nil).DeleteChallenge), ctx, sessionID)
}

// GetChallenge mocks base method.
func (m *MockChallengeSessionRepository) GetChallenge(ctx context.Context, sessionID string) (*domain.ChallengeSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChallenge", ctx, sessionID)
	ret0, _ := ret[0].(*domain.ChallengeSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChallenge indicates an expected call of GetChallenge.
func (mr *MockChallengeSessionRepositoryMockRecorder) GetChallenge(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChallenge", reflect.TypeOf((*MockChallengeSessionRepository)(nil).GetChallenge), ctx, sessionID)
}

// SaveChallenge mocks base method.
func (m *MockChallengeSessionRepository) SaveChallenge(ctx context.Context, sessionID string, challenge *domain.ChallengeSession, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveChallenge", ctx, sessionID, challenge, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveChallenge indicates an expected call of SaveChallenge.
func (mr *MockChallengeSessionRepositoryMockRecorder) SaveChallenge(ctx, sessionID, challenge, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveChallenge", reflect.TypeOf((*MockChallengeSessionRepository)(nil).SaveChallenge), ctx, sessionID, challenge, ttl)
}

// MockGlobalUserRepository is a mock of GlobalUserRepository interface.
type MockGlobalUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGlobalUserRepositoryMockRecorder
	isgomock struct{}
}

// MockGlobalUserRepositoryMockRecorder is the mock recorder for MockGlobalUserRepository.
type MockGlobalUserRepositoryMockRecorder struct {
	mock *MockGlobalUserRepository
}

// NewMockGlobalUserRepository creates a new mock instance.
func NewMockGlobalUserRepository(ctrl *gomock.Controller) *MockGlobalUserRepository {
	mock := &MockGlobalUserRepository{ctrl: ctrl}
	mock.recorder = &MockGlobalUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGlobalUserRepository) EXPECT() *MockGlobalUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockGlobalUserRepository) Create(tx *gorm.DB, user *domain.GlobalUser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", tx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockGlobalUserRepositoryMockRecorder) Create(tx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGlobalUserRepository)(nil).Create), tx, user)
}

// GetByID mocks base method.
func (m *MockGlobalUserRepository) GetByID(ctx context.Context, id string) (*domain.GlobalUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.GlobalUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockGlobalUserRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockGlobalUserRepository)(nil).GetByID), ctx, id)
}

// MockTenantRepository is a mock of TenantRepository interface.
type MockTenantRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTenantRepositoryMockRecorder
	isgomock struct{}
}

// MockTenantRepositoryMockRecorder is the mock recorder for MockTenantRepository.
type MockTenantRepositoryMockRecorder struct {
	mock *MockTenantRepository
}

// NewMockTenantRepository creates a new mock instance.
func NewMockTenantRepository(ctrl *gomock.Controller) *MockTenantRepository {
	mock := &MockTenantRepository{ctrl: ctrl}
	mock.recorder = &MockTenantRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantRepository) EXPECT() *MockTenantRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTenantRepository) Create(tenant *domain.Tenant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", tenant)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTenantRepositoryMockRecorder) Create(tenant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTenantRepository)(nil).Create), tenant)
}

// Delete mocks base method.
func (m *MockTenantRepository) Delete(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTenantRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTenantRepository)(nil).Delete), id)
}

// GetByID mocks base method.
func (m *MockTenantRepository) GetByID(id uuid.UUID) (*domain.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*domain.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTenantRepositoryMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTenantRepository)(nil).GetByID), id)
}

// GetByName mocks base method.
func (m *MockTenantRepository) GetByName(name string) (*domain.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", name)
	ret0, _ := ret[0].(*domain.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockTenantRepositoryMockRecorder) GetByName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockTenantRepository)(nil).GetByName), name)
}

// List mocks base method.
func (m *MockTenantRepository) List() ([]*domain.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]*domain.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTenantRepositoryMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTenantRepository)(nil).List))
}

// Update mocks base method.
func (m *MockTenantRepository) Update(tenant *domain.Tenant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", tenant)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTenantRepositoryMockRecorder) Update(tenant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTenantRepository)(nil).Update), tenant)
}

// MockUserIdentityChangeLogRepository is a mock of UserIdentityChangeLogRepository interface.
type MockUserIdentityChangeLogRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserIdentityChangeLogRepositoryMockRecorder
	isgomock struct{}
}

// MockUserIdentityChangeLogRepositoryMockRecorder is the mock recorder for MockUserIdentityChangeLogRepository.
type MockUserIdentityChangeLogRepositoryMockRecorder struct {
	mock *MockUserIdentityChangeLogRepository
}

// NewMockUserIdentityChangeLogRepository creates a new mock instance.
func NewMockUserIdentityChangeLogRepository(ctrl *gomock.Controller) *MockUserIdentityChangeLogRepository {
	mock := &MockUserIdentityChangeLogRepository{ctrl: ctrl}
	mock.recorder = &MockUserIdentityChangeLogRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserIdentityChangeLogRepository) EXPECT() *MockUserIdentityChangeLogRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserIdentityChangeLogRepository) Create(ctx context.Context, tx *gorm.DB, log *domain.UserIdentityChangeLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx, log)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserIdentityChangeLogRepositoryMockRecorder) Create(ctx, tx, log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserIdentityChangeLogRepository)(nil).Create), ctx, tx, log)
}

// ListByGlobalUserID mocks base method.
func (m *MockUserIdentityChangeLogRepository) ListByGlobalUserID(ctx context.Context, globalUserID uuid.UUID) ([]*domain.UserIdentityChangeLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByGlobalUserID", ctx, globalUserID)
	ret0, _ := ret[0].([]*domain.UserIdentityChangeLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByGlobalUserID indicates an expected call of ListByGlobalUserID.
func (mr *MockUserIdentityChangeLogRepositoryMockRecorder) ListByGlobalUserID(ctx, globalUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByGlobalUserID", reflect.TypeOf((*MockUserIdentityChangeLogRepository)(nil).ListByGlobalUserID), ctx, globalUserID)
}

// ListByTenantID mocks base method.
func (m *MockUserIdentityChangeLogRepository) ListByTenantID(ctx context.Context, tenantID uuid.UUID) ([]*domain.UserIdentityChangeLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByTenantID", ctx, tenantID)
	ret0, _ := ret[0].([]*domain.UserIdentityChangeLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByTenantID indicates an expected call of ListByTenantID.
func (mr *MockUserIdentityChangeLogRepositoryMockRecorder) ListByTenantID(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByTenantID", reflect.TypeOf((*MockUserIdentityChangeLogRepository)(nil).ListByTenantID), ctx, tenantID)
}

// MockUserIdentifierMappingRepository is a mock of UserIdentifierMappingRepository interface.
type MockUserIdentifierMappingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserIdentifierMappingRepositoryMockRecorder
	isgomock struct{}
}

// MockUserIdentifierMappingRepositoryMockRecorder is the mock recorder for MockUserIdentifierMappingRepository.
type MockUserIdentifierMappingRepositoryMockRecorder struct {
	mock *MockUserIdentifierMappingRepository
}

// NewMockUserIdentifierMappingRepository creates a new mock instance.
func NewMockUserIdentifierMappingRepository(ctrl *gomock.Controller) *MockUserIdentifierMappingRepository {
	mock := &MockUserIdentifierMappingRepository{ctrl: ctrl}
	mock.recorder = &MockUserIdentifierMappingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserIdentifierMappingRepository) EXPECT() *MockUserIdentifierMappingRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserIdentifierMappingRepository) Create(ctx context.Context, tx *gorm.DB, mapping *domain.UserIdentifierMapping) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx, mapping)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserIdentifierMappingRepositoryMockRecorder) Create(ctx, tx, mapping any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserIdentifierMappingRepository)(nil).Create), ctx, tx, mapping)
}

// GetByGlobalUserID mocks base method.
func (m *MockUserIdentifierMappingRepository) GetByGlobalUserID(ctx context.Context, globalUserID string) (*domain.UserIdentifierMapping, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByGlobalUserID", ctx, globalUserID)
	ret0, _ := ret[0].(*domain.UserIdentifierMapping)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByGlobalUserID indicates an expected call of GetByGlobalUserID.
func (mr *MockUserIdentifierMappingRepositoryMockRecorder) GetByGlobalUserID(ctx, globalUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByGlobalUserID", reflect.TypeOf((*MockUserIdentifierMappingRepository)(nil).GetByGlobalUserID), ctx, globalUserID)
}

// Upsert mocks base method.
func (m *MockUserIdentifierMappingRepository) Upsert(ctx context.Context, tx *gorm.DB, mapping *domain.UserIdentifierMapping) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, tx, mapping)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockUserIdentifierMappingRepositoryMockRecorder) Upsert(ctx, tx, mapping any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockUserIdentifierMappingRepository)(nil).Upsert), ctx, tx, mapping)
}

// MockUserIdentityRepository is a mock of UserIdentityRepository interface.
type MockUserIdentityRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserIdentityRepositoryMockRecorder
	isgomock struct{}
}

// MockUserIdentityRepositoryMockRecorder is the mock recorder for MockUserIdentityRepository.
type MockUserIdentityRepositoryMockRecorder struct {
	mock *MockUserIdentityRepository
}

// NewMockUserIdentityRepository creates a new mock instance.
func NewMockUserIdentityRepository(ctrl *gomock.Controller) *MockUserIdentityRepository {
	mock := &MockUserIdentityRepository{ctrl: ctrl}
	mock.recorder = &MockUserIdentityRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserIdentityRepository) EXPECT() *MockUserIdentityRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockUserIdentityRepository) Delete(tx *gorm.DB, identityID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", tx, identityID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserIdentityRepositoryMockRecorder) Delete(tx, identityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserIdentityRepository)(nil).Delete), tx, identityID)
}

// ExistsByTenantGlobalUserIDAndType mocks base method.
func (m *MockUserIdentityRepository) ExistsByTenantGlobalUserIDAndType(ctx context.Context, tenantID, globalUserID, identityType string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByTenantGlobalUserIDAndType", ctx, tenantID, globalUserID, identityType)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByTenantGlobalUserIDAndType indicates an expected call of ExistsByTenantGlobalUserIDAndType.
func (mr *MockUserIdentityRepositoryMockRecorder) ExistsByTenantGlobalUserIDAndType(ctx, tenantID, globalUserID, identityType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByTenantGlobalUserIDAndType", reflect.TypeOf((*MockUserIdentityRepository)(nil).ExistsByTenantGlobalUserIDAndType), ctx, tenantID, globalUserID, identityType)
}

// ExistsWithinTenant mocks base method.
func (m *MockUserIdentityRepository) ExistsWithinTenant(ctx context.Context, tenantID, identityType, value string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsWithinTenant", ctx, tenantID, identityType, value)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsWithinTenant indicates an expected call of ExistsWithinTenant.
func (mr *MockUserIdentityRepositoryMockRecorder) ExistsWithinTenant(ctx, tenantID, identityType, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsWithinTenant", reflect.TypeOf((*MockUserIdentityRepository)(nil).ExistsWithinTenant), ctx, tenantID, identityType, value)
}

// GetByGlobalUserIDAndTenantID mocks base method.
func (m *MockUserIdentityRepository) GetByGlobalUserIDAndTenantID(ctx context.Context, tx *gorm.DB, globalUserID, tenantID string) ([]*domain.UserIdentity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByGlobalUserIDAndTenantID", ctx, tx, globalUserID, tenantID)
	ret0, _ := ret[0].([]*domain.UserIdentity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByGlobalUserIDAndTenantID indicates an expected call of GetByGlobalUserIDAndTenantID.
func (mr *MockUserIdentityRepositoryMockRecorder) GetByGlobalUserIDAndTenantID(ctx, tx, globalUserID, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByGlobalUserIDAndTenantID", reflect.TypeOf((*MockUserIdentityRepository)(nil).GetByGlobalUserIDAndTenantID), ctx, tx, globalUserID, tenantID)
}

// GetByID mocks base method.
func (m *MockUserIdentityRepository) GetByID(ctx context.Context, tx *gorm.DB, identityID string) (*domain.UserIdentity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, tx, identityID)
	ret0, _ := ret[0].(*domain.UserIdentity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserIdentityRepositoryMockRecorder) GetByID(ctx, tx, identityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserIdentityRepository)(nil).GetByID), ctx, tx, identityID)
}

// GetByTenantAndKratosUserID mocks base method.
func (m *MockUserIdentityRepository) GetByTenantAndKratosUserID(ctx context.Context, tx *gorm.DB, tenantID, kratosUserID string) (*domain.UserIdentity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTenantAndKratosUserID", ctx, tx, tenantID, kratosUserID)
	ret0, _ := ret[0].(*domain.UserIdentity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTenantAndKratosUserID indicates an expected call of GetByTenantAndKratosUserID.
func (mr *MockUserIdentityRepositoryMockRecorder) GetByTenantAndKratosUserID(ctx, tx, tenantID, kratosUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTenantAndKratosUserID", reflect.TypeOf((*MockUserIdentityRepository)(nil).GetByTenantAndKratosUserID), ctx, tx, tenantID, kratosUserID)
}

// GetByTypeAndValue mocks base method.
func (m *MockUserIdentityRepository) GetByTypeAndValue(ctx context.Context, tx *gorm.DB, tenantID, identityType, value string) (*domain.UserIdentity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTypeAndValue", ctx, tx, tenantID, identityType, value)
	ret0, _ := ret[0].(*domain.UserIdentity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTypeAndValue indicates an expected call of GetByTypeAndValue.
func (mr *MockUserIdentityRepositoryMockRecorder) GetByTypeAndValue(ctx, tx, tenantID, identityType, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTypeAndValue", reflect.TypeOf((*MockUserIdentityRepository)(nil).GetByTypeAndValue), ctx, tx, tenantID, identityType, value)
}

// InsertOnceByKratosUserAndType mocks base method.
func (m *MockUserIdentityRepository) InsertOnceByKratosUserAndType(ctx context.Context, tx *gorm.DB, tenantID, kratosUserID, globalUserID, idType, value string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOnceByKratosUserAndType", ctx, tx, tenantID, kratosUserID, globalUserID, idType, value)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertOnceByKratosUserAndType indicates an expected call of InsertOnceByKratosUserAndType.
func (mr *MockUserIdentityRepositoryMockRecorder) InsertOnceByKratosUserAndType(ctx, tx, tenantID, kratosUserID, globalUserID, idType, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOnceByKratosUserAndType", reflect.TypeOf((*MockUserIdentityRepository)(nil).InsertOnceByKratosUserAndType), ctx, tx, tenantID, kratosUserID, globalUserID, idType, value)
}

// ListByTenantAndKratosUserID mocks base method.
func (m *MockUserIdentityRepository) ListByTenantAndKratosUserID(ctx context.Context, tx *gorm.DB, tenantID, kratosUserID string) ([]*domain.UserIdentity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByTenantAndKratosUserID", ctx, tx, tenantID, kratosUserID)
	ret0, _ := ret[0].([]*domain.UserIdentity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByTenantAndKratosUserID indicates an expected call of ListByTenantAndKratosUserID.
func (mr *MockUserIdentityRepositoryMockRecorder) ListByTenantAndKratosUserID(ctx, tx, tenantID, kratosUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByTenantAndKratosUserID", reflect.TypeOf((*MockUserIdentityRepository)(nil).ListByTenantAndKratosUserID), ctx, tx, tenantID, kratosUserID)
}

// Update mocks base method.
func (m *MockUserIdentityRepository) Update(tx *gorm.DB, identity *domain.UserIdentity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", tx, identity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserIdentityRepositoryMockRecorder) Update(tx, identity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserIdentityRepository)(nil).Update), tx, identity)
}
