// Code generated by MockGen. DO NOT EDIT.
// Source: ./infrastructures/otp_queue/types/otp_queue.go
//
// Generated by this command:
//
//	mockgen -source=./infrastructures/otp_queue/types/otp_queue.go -package=mock_types -destination=mocks/infrastructures/otp_queue/types/mock_otp_queue.go
//

// Package mock_types is a generated GoMock package.
package mock_types

import (
	context "context"
	reflect "reflect"
	time "time"

	types "github.com/lifenetwork-ai/iam-service/infrastructures/otp_queue/types"
	gomock "go.uber.org/mock/gomock"
)

// MockOTPQueueRepository is a mock of OTPQueueRepository interface.
type MockOTPQueueRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOTPQueueRepositoryMockRecorder
	isgomock struct{}
}

// MockOTPQueueRepositoryMockRecorder is the mock recorder for MockOTPQueueRepository.
type MockOTPQueueRepositoryMockRecorder struct {
	mock *MockOTPQueueRepository
}

// NewMockOTPQueueRepository creates a new mock instance.
func NewMockOTPQueueRepository(ctrl *gomock.Controller) *MockOTPQueueRepository {
	mock := &MockOTPQueueRepository{ctrl: ctrl}
	mock.recorder = &MockOTPQueueRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOTPQueueRepository) EXPECT() *MockOTPQueueRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockOTPQueueRepository) Delete(ctx context.Context, tenantName, receiver string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, tenantName, receiver)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockOTPQueueRepositoryMockRecorder) Delete(ctx, tenantName, receiver any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockOTPQueueRepository)(nil).Delete), ctx, tenantName, receiver)
}

// DeleteRetryTask mocks base method.
func (m *MockOTPQueueRepository) DeleteRetryTask(ctx context.Context, task types.RetryTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRetryTask", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRetryTask indicates an expected call of DeleteRetryTask.
func (mr *MockOTPQueueRepositoryMockRecorder) DeleteRetryTask(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRetryTask", reflect.TypeOf((*MockOTPQueueRepository)(nil).DeleteRetryTask), ctx, task)
}

// Enqueue mocks base method.
func (m *MockOTPQueueRepository) Enqueue(ctx context.Context, item types.OTPQueueItem, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enqueue", ctx, item, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockOTPQueueRepositoryMockRecorder) Enqueue(ctx, item, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockOTPQueueRepository)(nil).Enqueue), ctx, item, ttl)
}

// EnqueueRetry mocks base method.
func (m *MockOTPQueueRepository) EnqueueRetry(ctx context.Context, task types.RetryTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueRetry", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnqueueRetry indicates an expected call of EnqueueRetry.
func (mr *MockOTPQueueRepositoryMockRecorder) EnqueueRetry(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueRetry", reflect.TypeOf((*MockOTPQueueRepository)(nil).EnqueueRetry), ctx, task)
}

// Get mocks base method.
func (m *MockOTPQueueRepository) Get(ctx context.Context, tenantName, receiver string) (*types.OTPQueueItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, tenantName, receiver)
	ret0, _ := ret[0].(*types.OTPQueueItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockOTPQueueRepositoryMockRecorder) Get(ctx, tenantName, receiver any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockOTPQueueRepository)(nil).Get), ctx, tenantName, receiver)
}

// GetDueRetryTasks mocks base method.
func (m *MockOTPQueueRepository) GetDueRetryTasks(ctx context.Context, now time.Time) ([]types.RetryTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDueRetryTasks", ctx, now)
	ret0, _ := ret[0].([]types.RetryTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDueRetryTasks indicates an expected call of GetDueRetryTasks.
func (mr *MockOTPQueueRepositoryMockRecorder) GetDueRetryTasks(ctx, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDueRetryTasks", reflect.TypeOf((*MockOTPQueueRepository)(nil).GetDueRetryTasks), ctx, now)
}

// ListReceivers mocks base method.
func (m *MockOTPQueueRepository) ListReceivers(ctx context.Context, tenantName string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReceivers", ctx, tenantName)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListReceivers indicates an expected call of ListReceivers.
func (mr *MockOTPQueueRepositoryMockRecorder) ListReceivers(ctx, tenantName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReceivers", reflect.TypeOf((*MockOTPQueueRepository)(nil).ListReceivers), ctx, tenantName)
}
