// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/genefriendway/human-network-iam/conf"
	"github.com/genefriendway/human-network-iam/internal/adapters/identity/organization"
	"github.com/genefriendway/human-network-iam/internal/interfaces"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// Init ucase
func GetOrganizationUseCase(db *gorm.DB, config *conf.Configuration) interfaces.IdentityOrganizationUseCase {
	identityOrganizationRepository := identity_organization.NewIdentityOrganizationRepository(db)
	identityOrganizationUseCase := identity_organization.NewIdentityOrganizationUseCase(identityOrganizationRepository)
	return identityOrganizationUseCase
}

// wire.go:

// UCase set
var organizationUseCaseSet = wire.NewSet(identity_organization.NewIdentityOrganizationRepository, identity_organization.NewIdentityOrganizationUseCase)
