// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/genefriendway/human-network-iam/conf"
	"github.com/genefriendway/human-network-iam/internal/adapters/repositories"
	"github.com/genefriendway/human-network-iam/internal/interfaces"
	"github.com/genefriendway/human-network-iam/internal/ucases"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// Init ucase
func GetOrganizationUseCase(db *gorm.DB, config *conf.Configuration) interfaces.IdentityOrganizationUseCase {
	identityOrganizationRepository := repositories.NewIdentityOrganizationRepository(db)
	identityOrganizationUseCase := ucases.NewIdentityOrganizationUseCase(identityOrganizationRepository)
	return identityOrganizationUseCase
}

func GetUserUseCase(db *gorm.DB, config *conf.Configuration) interfaces.IdentityUserUseCase {
	identityUserRepository := repositories.NewIdentityUserRepository(db)
	identityUserUseCase := ucases.NewIdentityUserUseCase(identityUserRepository)
	return identityUserUseCase
}

// wire.go:

// UCase set
var organizationUseCaseSet = wire.NewSet(repositories.NewIdentityOrganizationRepository, ucases.NewIdentityOrganizationUseCase)

var userCaseSet = wire.NewSet(repositories.NewIdentityUserRepository, ucases.NewIdentityUserUseCase)
