// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/adapters/services/types/kratos.go
//
// Generated by this command:
//
//	mockgen -source=./internal/adapters/services/types/kratos.go -package=mock_types -destination=mocks/adapters/services/types/mock_kratos.go
//

// Package mock_types is a generated GoMock package.
package mock_types
