// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/adapters/services/sms/provider/interface.go
//
// Generated by this command:
//
//	mockgen -source=./internal/adapters/services/sms/provider/interface.go -package=mock_provider -destination=mocks/adapters/services/sms/provider/mock_interface.go
//

// Package mock_provider is a generated GoMock package.
package mock_provider

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockSMSProvider is a mock of SMSProvider interface.
type MockSMSProvider struct {
	ctrl     *gomock.Controller
	recorder *MockSMSProviderMockRecorder
	isgomock struct{}
}

// MockSMSProviderMockRecorder is the mock recorder for MockSMSProvider.
type MockSMSProviderMockRecorder struct {
	mock *MockSMSProvider
}

// NewMockSMSProvider creates a new mock instance.
func NewMockSMSProvider(ctrl *gomock.Controller) *MockSMSProvider {
	mock := &MockSMSProvider{ctrl: ctrl}
	mock.recorder = &MockSMSProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSMSProvider) EXPECT() *MockSMSProviderMockRecorder {
	return m.recorder
}

// GetChannelType mocks base method.
func (m *MockSMSProvider) GetChannelType() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChannelType")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetChannelType indicates an expected call of GetChannelType.
func (mr *MockSMSProviderMockRecorder) GetChannelType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChannelType", reflect.TypeOf((*MockSMSProvider)(nil).GetChannelType))
}

// HealthCheck mocks base method.
func (m *MockSMSProvider) HealthCheck(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockSMSProviderMockRecorder) HealthCheck(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockSMSProvider)(nil).HealthCheck), ctx)
}

// RefreshToken mocks base method.
func (m *MockSMSProvider) RefreshToken(ctx context.Context, refreshToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", ctx, refreshToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockSMSProviderMockRecorder) RefreshToken(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockSMSProvider)(nil).RefreshToken), ctx, refreshToken)
}

// SendOTP mocks base method.
func (m *MockSMSProvider) SendOTP(ctx context.Context, tenantName, receiver, otp string, ttl time.Duration, lang string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendOTP", ctx, tenantName, receiver, otp, ttl, lang)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendOTP indicates an expected call of SendOTP.
func (mr *MockSMSProviderMockRecorder) SendOTP(ctx, tenantName, receiver, otp, ttl, lang any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendOTP", reflect.TypeOf((*MockSMSProvider)(nil).SendOTP), ctx, tenantName, receiver, otp, ttl, lang)
}
