// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/ucases/interfaces/admin.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/ucases/interfaces/admin.go -package=mock_interfaces -destination=mocks/domain/ucases/interfaces/mock_admin.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"

	domain "github.com/lifenetwork-ai/iam-service/internal/domain/entities"
	types "github.com/lifenetwork-ai/iam-service/internal/domain/types"
	errors "github.com/lifenetwork-ai/iam-service/internal/domain/ucases/errors"
	gomock "go.uber.org/mock/gomock"
)

// MockAdminUseCase is a mock of AdminUseCase interface.
type MockAdminUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockAdminUseCaseMockRecorder
	isgomock struct{}
}

// MockAdminUseCaseMockRecorder is the mock recorder for MockAdminUseCase.
type MockAdminUseCaseMockRecorder struct {
	mock *MockAdminUseCase
}

// NewMockAdminUseCase creates a new mock instance.
func NewMockAdminUseCase(ctrl *gomock.Controller) *MockAdminUseCase {
	mock := &MockAdminUseCase{ctrl: ctrl}
	mock.recorder = &MockAdminUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminUseCase) EXPECT() *MockAdminUseCaseMockRecorder {
	return m.recorder
}

// CreateAdminAccount mocks base method.
func (m *MockAdminUseCase) CreateAdminAccount(ctx context.Context, username, password, role string) (*domain.AdminAccount, *errors.DomainError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAdminAccount", ctx, username, password, role)
	ret0, _ := ret[0].(*domain.AdminAccount)
	ret1, _ := ret[1].(*errors.DomainError)
	return ret0, ret1
}

// CreateAdminAccount indicates an expected call of CreateAdminAccount.
func (mr *MockAdminUseCaseMockRecorder) CreateAdminAccount(ctx, username, password, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAdminAccount", reflect.TypeOf((*MockAdminUseCase)(nil).CreateAdminAccount), ctx, username, password, role)
}

// CreateTenant mocks base method.
func (m *MockAdminUseCase) CreateTenant(ctx context.Context, name, publicURL, adminURL string) (*domain.Tenant, *errors.DomainError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTenant", ctx, name, publicURL, adminURL)
	ret0, _ := ret[0].(*domain.Tenant)
	ret1, _ := ret[1].(*errors.DomainError)
	return ret0, ret1
}

// CreateTenant indicates an expected call of CreateTenant.
func (mr *MockAdminUseCaseMockRecorder) CreateTenant(ctx, name, publicURL, adminURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTenant", reflect.TypeOf((*MockAdminUseCase)(nil).CreateTenant), ctx, name, publicURL, adminURL)
}

// DeleteTenant mocks base method.
func (m *MockAdminUseCase) DeleteTenant(ctx context.Context, id string) (*domain.Tenant, *errors.DomainError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTenant", ctx, id)
	ret0, _ := ret[0].(*domain.Tenant)
	ret1, _ := ret[1].(*errors.DomainError)
	return ret0, ret1
}

// DeleteTenant indicates an expected call of DeleteTenant.
func (mr *MockAdminUseCaseMockRecorder) DeleteTenant(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTenant", reflect.TypeOf((*MockAdminUseCase)(nil).DeleteTenant), ctx, id)
}

// GetAdminAccountByUsername mocks base method.
func (m *MockAdminUseCase) GetAdminAccountByUsername(ctx context.Context, username string) (*domain.AdminAccount, *errors.DomainError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdminAccountByUsername", ctx, username)
	ret0, _ := ret[0].(*domain.AdminAccount)
	ret1, _ := ret[1].(*errors.DomainError)
	return ret0, ret1
}

// GetAdminAccountByUsername indicates an expected call of GetAdminAccountByUsername.
func (mr *MockAdminUseCaseMockRecorder) GetAdminAccountByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdminAccountByUsername", reflect.TypeOf((*MockAdminUseCase)(nil).GetAdminAccountByUsername), ctx, username)
}

// GetTenantByID mocks base method.
func (m *MockAdminUseCase) GetTenantByID(ctx context.Context, id string) (*domain.Tenant, *errors.DomainError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenantByID", ctx, id)
	ret0, _ := ret[0].(*domain.Tenant)
	ret1, _ := ret[1].(*errors.DomainError)
	return ret0, ret1
}

// GetTenantByID indicates an expected call of GetTenantByID.
func (mr *MockAdminUseCaseMockRecorder) GetTenantByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenantByID", reflect.TypeOf((*MockAdminUseCase)(nil).GetTenantByID), ctx, id)
}

// ListTenants mocks base method.
func (m *MockAdminUseCase) ListTenants(ctx context.Context, page, size int, keyword string) (*types.PaginatedResponse[*domain.Tenant], *errors.DomainError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTenants", ctx, page, size, keyword)
	ret0, _ := ret[0].(*types.PaginatedResponse[*domain.Tenant])
	ret1, _ := ret[1].(*errors.DomainError)
	return ret0, ret1
}

// ListTenants indicates an expected call of ListTenants.
func (mr *MockAdminUseCaseMockRecorder) ListTenants(ctx, page, size, keyword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTenants", reflect.TypeOf((*MockAdminUseCase)(nil).ListTenants), ctx, page, size, keyword)
}

// UpdateTenant mocks base method.
func (m *MockAdminUseCase) UpdateTenant(ctx context.Context, id, name, publicURL, adminURL string) (*domain.Tenant, *errors.DomainError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTenant", ctx, id, name, publicURL, adminURL)
	ret0, _ := ret[0].(*domain.Tenant)
	ret1, _ := ret[1].(*errors.DomainError)
	return ret0, ret1
}

// UpdateTenant indicates an expected call of UpdateTenant.
func (mr *MockAdminUseCaseMockRecorder) UpdateTenant(ctx, id, name, publicURL, adminURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTenant", reflect.TypeOf((*MockAdminUseCase)(nil).UpdateTenant), ctx, id, name, publicURL, adminURL)
}
