// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/ucases/interfaces/courier.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/ucases/interfaces/courier.go -package=mock_interfaces -destination=mocks/domain/ucases/interfaces/mock_courier.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"
	time "time"

	errors "github.com/lifenetwork-ai/iam-service/internal/domain/ucases/errors"
	types "github.com/lifenetwork-ai/iam-service/internal/domain/ucases/types"
	gomock "go.uber.org/mock/gomock"
)

// MockCourierUseCase is a mock of CourierUseCase interface.
type MockCourierUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCourierUseCaseMockRecorder
	isgomock struct{}
}

// MockCourierUseCaseMockRecorder is the mock recorder for MockCourierUseCase.
type MockCourierUseCaseMockRecorder struct {
	mock *MockCourierUseCase
}

// NewMockCourierUseCase creates a new mock instance.
func NewMockCourierUseCase(ctrl *gomock.Controller) *MockCourierUseCase {
	mock := &MockCourierUseCase{ctrl: ctrl}
	mock.recorder = &MockCourierUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCourierUseCase) EXPECT() *MockCourierUseCaseMockRecorder {
	return m.recorder
}

// ChooseChannel mocks base method.
func (m *MockCourierUseCase) ChooseChannel(ctx context.Context, tenantName, receiver, channel string) *errors.DomainError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChooseChannel", ctx, tenantName, receiver, channel)
	ret0, _ := ret[0].(*errors.DomainError)
	return ret0
}

// ChooseChannel indicates an expected call of ChooseChannel.
func (mr *MockCourierUseCaseMockRecorder) ChooseChannel(ctx, tenantName, receiver, channel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChooseChannel", reflect.TypeOf((*MockCourierUseCase)(nil).ChooseChannel), ctx, tenantName, receiver, channel)
}

// DeliverOTP mocks base method.
func (m *MockCourierUseCase) DeliverOTP(ctx context.Context, tenantName, receiver string) *errors.DomainError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeliverOTP", ctx, tenantName, receiver)
	ret0, _ := ret[0].(*errors.DomainError)
	return ret0
}

// DeliverOTP indicates an expected call of DeliverOTP.
func (mr *MockCourierUseCaseMockRecorder) DeliverOTP(ctx, tenantName, receiver any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeliverOTP", reflect.TypeOf((*MockCourierUseCase)(nil).DeliverOTP), ctx, tenantName, receiver)
}

// GetAvailableChannels mocks base method.
func (m *MockCourierUseCase) GetAvailableChannels(ctx context.Context, tenantName, receiver string) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableChannels", ctx, tenantName, receiver)
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetAvailableChannels indicates an expected call of GetAvailableChannels.
func (mr *MockCourierUseCaseMockRecorder) GetAvailableChannels(ctx, tenantName, receiver any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableChannels", reflect.TypeOf((*MockCourierUseCase)(nil).GetAvailableChannels), ctx, tenantName, receiver)
}

// GetChannel mocks base method.
func (m *MockCourierUseCase) GetChannel(ctx context.Context, tenantName, receiver string) (types.ChooseChannelResponse, *errors.DomainError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChannel", ctx, tenantName, receiver)
	ret0, _ := ret[0].(types.ChooseChannelResponse)
	ret1, _ := ret[1].(*errors.DomainError)
	return ret0, ret1
}

// GetChannel indicates an expected call of GetChannel.
func (mr *MockCourierUseCaseMockRecorder) GetChannel(ctx, tenantName, receiver any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChannel", reflect.TypeOf((*MockCourierUseCase)(nil).GetChannel), ctx, tenantName, receiver)
}

// ReceiveOTP mocks base method.
func (m *MockCourierUseCase) ReceiveOTP(ctx context.Context, receiver, body string) *errors.DomainError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReceiveOTP", ctx, receiver, body)
	ret0, _ := ret[0].(*errors.DomainError)
	return ret0
}

// ReceiveOTP indicates an expected call of ReceiveOTP.
func (mr *MockCourierUseCaseMockRecorder) ReceiveOTP(ctx, receiver, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReceiveOTP", reflect.TypeOf((*MockCourierUseCase)(nil).ReceiveOTP), ctx, receiver, body)
}

// RetryFailedOTPs mocks base method.
func (m *MockCourierUseCase) RetryFailedOTPs(ctx context.Context, now time.Time) (int, *errors.DomainError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetryFailedOTPs", ctx, now)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(*errors.DomainError)
	return ret0, ret1
}

// RetryFailedOTPs indicates an expected call of RetryFailedOTPs.
func (mr *MockCourierUseCaseMockRecorder) RetryFailedOTPs(ctx, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetryFailedOTPs", reflect.TypeOf((*MockCourierUseCase)(nil).RetryFailedOTPs), ctx, now)
}
