// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/ucases/interfaces/sms_token.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/ucases/interfaces/sms_token.go -package=mock_interfaces -destination=mocks/domain/ucases/interfaces/mock_sms_token.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/lifenetwork-ai/iam-service/internal/domain/entities"
	errors "github.com/lifenetwork-ai/iam-service/internal/domain/ucases/errors"
	gomock "go.uber.org/mock/gomock"
)

// MockSmsTokenUseCase is a mock of SmsTokenUseCase interface.
type MockSmsTokenUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockSmsTokenUseCaseMockRecorder
	isgomock struct{}
}

// MockSmsTokenUseCaseMockRecorder is the mock recorder for MockSmsTokenUseCase.
type MockSmsTokenUseCaseMockRecorder struct {
	mock *MockSmsTokenUseCase
}

// NewMockSmsTokenUseCase creates a new mock instance.
func NewMockSmsTokenUseCase(ctrl *gomock.Controller) *MockSmsTokenUseCase {
	mock := &MockSmsTokenUseCase{ctrl: ctrl}
	mock.recorder = &MockSmsTokenUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSmsTokenUseCase) EXPECT() *MockSmsTokenUseCaseMockRecorder {
	return m.recorder
}

// CreateOrUpdateZaloToken mocks base method.
func (m *MockSmsTokenUseCase) CreateOrUpdateZaloToken(ctx context.Context, tenantID uuid.UUID, appID, secretKey, refreshToken, accessToken, otpTemplateID string) *errors.DomainError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateZaloToken", ctx, tenantID, appID, secretKey, refreshToken, accessToken, otpTemplateID)
	ret0, _ := ret[0].(*errors.DomainError)
	return ret0
}

// CreateOrUpdateZaloToken indicates an expected call of CreateOrUpdateZaloToken.
func (mr *MockSmsTokenUseCaseMockRecorder) CreateOrUpdateZaloToken(ctx, tenantID, appID, secretKey, refreshToken, accessToken, otpTemplateID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateZaloToken", reflect.TypeOf((*MockSmsTokenUseCase)(nil).CreateOrUpdateZaloToken), ctx, tenantID, appID, secretKey, refreshToken, accessToken, otpTemplateID)
}

// DeleteZaloToken mocks base method.
func (m *MockSmsTokenUseCase) DeleteZaloToken(ctx context.Context, tenantID uuid.UUID) *errors.DomainError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteZaloToken", ctx, tenantID)
	ret0, _ := ret[0].(*errors.DomainError)
	return ret0
}

// DeleteZaloToken indicates an expected call of DeleteZaloToken.
func (mr *MockSmsTokenUseCaseMockRecorder) DeleteZaloToken(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteZaloToken", reflect.TypeOf((*MockSmsTokenUseCase)(nil).DeleteZaloToken), ctx, tenantID)
}

// GetEncryptedZaloToken mocks base method.
func (m *MockSmsTokenUseCase) GetEncryptedZaloToken(ctx context.Context, tenantID uuid.UUID) (*domain.ZaloToken, *errors.DomainError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEncryptedZaloToken", ctx, tenantID)
	ret0, _ := ret[0].(*domain.ZaloToken)
	ret1, _ := ret[1].(*errors.DomainError)
	return ret0, ret1
}

// GetEncryptedZaloToken indicates an expected call of GetEncryptedZaloToken.
func (mr *MockSmsTokenUseCaseMockRecorder) GetEncryptedZaloToken(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEncryptedZaloToken", reflect.TypeOf((*MockSmsTokenUseCase)(nil).GetEncryptedZaloToken), ctx, tenantID)
}

// GetZaloToken mocks base method.
func (m *MockSmsTokenUseCase) GetZaloToken(ctx context.Context, tenantID uuid.UUID) (*domain.ZaloToken, *errors.DomainError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetZaloToken", ctx, tenantID)
	ret0, _ := ret[0].(*domain.ZaloToken)
	ret1, _ := ret[1].(*errors.DomainError)
	return ret0, ret1
}

// GetZaloToken indicates an expected call of GetZaloToken.
func (mr *MockSmsTokenUseCaseMockRecorder) GetZaloToken(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetZaloToken", reflect.TypeOf((*MockSmsTokenUseCase)(nil).GetZaloToken), ctx, tenantID)
}

// RefreshZaloToken mocks base method.
func (m *MockSmsTokenUseCase) RefreshZaloToken(ctx context.Context, tenantID uuid.UUID, refreshToken string) *errors.DomainError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshZaloToken", ctx, tenantID, refreshToken)
	ret0, _ := ret[0].(*errors.DomainError)
	return ret0
}

// RefreshZaloToken indicates an expected call of RefreshZaloToken.
func (mr *MockSmsTokenUseCaseMockRecorder) RefreshZaloToken(ctx, tenantID, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshZaloToken", reflect.TypeOf((*MockSmsTokenUseCase)(nil).RefreshZaloToken), ctx, tenantID, refreshToken)
}

// ZaloHealthCheck mocks base method.
func (m *MockSmsTokenUseCase) ZaloHealthCheck(ctx context.Context, tenantID uuid.UUID) *errors.DomainError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ZaloHealthCheck", ctx, tenantID)
	ret0, _ := ret[0].(*errors.DomainError)
	return ret0
}

// ZaloHealthCheck indicates an expected call of ZaloHealthCheck.
func (mr *MockSmsTokenUseCaseMockRecorder) ZaloHealthCheck(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ZaloHealthCheck", reflect.TypeOf((*MockSmsTokenUseCase)(nil).ZaloHealthCheck), ctx, tenantID)
}
