// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/ucases/interfaces/identity_user.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/ucases/interfaces/identity_user.go -package=mock_interfaces -destination=mocks/domain/ucases/interfaces/mock_identity_user.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	errors "github.com/lifenetwork-ai/iam-service/internal/domain/ucases/errors"
	types "github.com/lifenetwork-ai/iam-service/internal/domain/ucases/types"
	gomock "go.uber.org/mock/gomock"
)

// MockIdentityUserUseCase is a mock of IdentityUserUseCase interface.
type MockIdentityUserUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityUserUseCaseMockRecorder
	isgomock struct{}
}

// MockIdentityUserUseCaseMockRecorder is the mock recorder for MockIdentityUserUseCase.
type MockIdentityUserUseCaseMockRecorder struct {
	mock *MockIdentityUserUseCase
}

// NewMockIdentityUserUseCase creates a new mock instance.
func NewMockIdentityUserUseCase(ctrl *gomock.Controller) *MockIdentityUserUseCase {
	mock := &MockIdentityUserUseCase{ctrl: ctrl}
	mock.recorder = &MockIdentityUserUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityUserUseCase) EXPECT() *MockIdentityUserUseCaseMockRecorder {
	return m.recorder
}

// AddNewIdentifier mocks base method.
func (m *MockIdentityUserUseCase) AddNewIdentifier(ctx context.Context, tenantID uuid.UUID, globalUserID, identifier, identifierType string) (*types.IdentityUserChallengeResponse, *errors.DomainError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNewIdentifier", ctx, tenantID, globalUserID, identifier, identifierType)
	ret0, _ := ret[0].(*types.IdentityUserChallengeResponse)
	ret1, _ := ret[1].(*errors.DomainError)
	return ret0, ret1
}

// AddNewIdentifier indicates an expected call of AddNewIdentifier.
func (mr *MockIdentityUserUseCaseMockRecorder) AddNewIdentifier(ctx, tenantID, globalUserID, identifier, identifierType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNewIdentifier", reflect.TypeOf((*MockIdentityUserUseCase)(nil).AddNewIdentifier), ctx, tenantID, globalUserID, identifier, identifierType)
}

// ChallengeVerification mocks base method.
func (m *MockIdentityUserUseCase) ChallengeVerification(ctx context.Context, tenantID uuid.UUID, identifier string) (*types.IdentityUserChallengeResponse, *errors.DomainError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChallengeVerification", ctx, tenantID, identifier)
	ret0, _ := ret[0].(*types.IdentityUserChallengeResponse)
	ret1, _ := ret[1].(*errors.DomainError)
	return ret0, ret1
}

// ChallengeVerification indicates an expected call of ChallengeVerification.
func (mr *MockIdentityUserUseCaseMockRecorder) ChallengeVerification(ctx, tenantID, identifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChallengeVerification", reflect.TypeOf((*MockIdentityUserUseCase)(nil).ChallengeVerification), ctx, tenantID, identifier)
}

// ChallengeWithEmail mocks base method.
func (m *MockIdentityUserUseCase) ChallengeWithEmail(ctx context.Context, tenantID uuid.UUID, email string) (*types.IdentityUserChallengeResponse, *errors.DomainError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChallengeWithEmail", ctx, tenantID, email)
	ret0, _ := ret[0].(*types.IdentityUserChallengeResponse)
	ret1, _ := ret[1].(*errors.DomainError)
	return ret0, ret1
}

// ChallengeWithEmail indicates an expected call of ChallengeWithEmail.
func (mr *MockIdentityUserUseCaseMockRecorder) ChallengeWithEmail(ctx, tenantID, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChallengeWithEmail", reflect.TypeOf((*MockIdentityUserUseCase)(nil).ChallengeWithEmail), ctx, tenantID, email)
}

// ChallengeWithPhone mocks base method.
func (m *MockIdentityUserUseCase) ChallengeWithPhone(ctx context.Context, tenantID uuid.UUID, phone string) (*types.IdentityUserChallengeResponse, *errors.DomainError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChallengeWithPhone", ctx, tenantID, phone)
	ret0, _ := ret[0].(*types.IdentityUserChallengeResponse)
	ret1, _ := ret[1].(*errors.DomainError)
	return ret0, ret1
}

// ChallengeWithPhone indicates an expected call of ChallengeWithPhone.
func (mr *MockIdentityUserUseCaseMockRecorder) ChallengeWithPhone(ctx, tenantID, phone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChallengeWithPhone", reflect.TypeOf((*MockIdentityUserUseCase)(nil).ChallengeWithPhone), ctx, tenantID, phone)
}

// ChangeIdentifier mocks base method.
func (m *MockIdentityUserUseCase) ChangeIdentifier(ctx context.Context, globalUserID string, tenantID uuid.UUID, tenantUserID, newIdentifier string) (*types.IdentityUserChallengeResponse, *errors.DomainError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeIdentifier", ctx, globalUserID, tenantID, tenantUserID, newIdentifier)
	ret0, _ := ret[0].(*types.IdentityUserChallengeResponse)
	ret1, _ := ret[1].(*errors.DomainError)
	return ret0, ret1
}

// ChangeIdentifier indicates an expected call of ChangeIdentifier.
func (mr *MockIdentityUserUseCaseMockRecorder) ChangeIdentifier(ctx, globalUserID, tenantID, tenantUserID, newIdentifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeIdentifier", reflect.TypeOf((*MockIdentityUserUseCase)(nil).ChangeIdentifier), ctx, globalUserID, tenantID, tenantUserID, newIdentifier)
}

// CheckIdentifier mocks base method.
func (m *MockIdentityUserUseCase) CheckIdentifier(ctx context.Context, tenantID uuid.UUID, identifier string) (bool, string, *errors.DomainError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckIdentifier", ctx, tenantID, identifier)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(*errors.DomainError)
	return ret0, ret1, ret2
}

// CheckIdentifier indicates an expected call of CheckIdentifier.
func (mr *MockIdentityUserUseCaseMockRecorder) CheckIdentifier(ctx, tenantID, identifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckIdentifier", reflect.TypeOf((*MockIdentityUserUseCase)(nil).CheckIdentifier), ctx, tenantID, identifier)
}

// DeleteIdentifier mocks base method.
func (m *MockIdentityUserUseCase) DeleteIdentifier(ctx context.Context, globalUserID string, tenantID uuid.UUID, tenantUserID, identifierType string) *errors.DomainError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIdentifier", ctx, globalUserID, tenantID, tenantUserID, identifierType)
	ret0, _ := ret[0].(*errors.DomainError)
	return ret0
}

// DeleteIdentifier indicates an expected call of DeleteIdentifier.
func (mr *MockIdentityUserUseCaseMockRecorder) DeleteIdentifier(ctx, globalUserID, tenantID, tenantUserID, identifierType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIdentifier", reflect.TypeOf((*MockIdentityUserUseCase)(nil).DeleteIdentifier), ctx, globalUserID, tenantID, tenantUserID, identifierType)
}

// Login mocks base method.
func (m *MockIdentityUserUseCase) Login(ctx context.Context, tenantID uuid.UUID, username, password string) (*types.IdentityUserAuthResponse, *errors.DomainError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, tenantID, username, password)
	ret0, _ := ret[0].(*types.IdentityUserAuthResponse)
	ret1, _ := ret[1].(*errors.DomainError)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockIdentityUserUseCaseMockRecorder) Login(ctx, tenantID, username, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockIdentityUserUseCase)(nil).Login), ctx, tenantID, username, password)
}

// Logout mocks base method.
func (m *MockIdentityUserUseCase) Logout(ctx context.Context, tenantID uuid.UUID) *errors.DomainError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, tenantID)
	ret0, _ := ret[0].(*errors.DomainError)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockIdentityUserUseCaseMockRecorder) Logout(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockIdentityUserUseCase)(nil).Logout), ctx, tenantID)
}

// Profile mocks base method.
func (m *MockIdentityUserUseCase) Profile(ctx context.Context, tenantID uuid.UUID) (*types.IdentityUserResponse, *errors.DomainError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Profile", ctx, tenantID)
	ret0, _ := ret[0].(*types.IdentityUserResponse)
	ret1, _ := ret[1].(*errors.DomainError)
	return ret0, ret1
}

// Profile indicates an expected call of Profile.
func (mr *MockIdentityUserUseCaseMockRecorder) Profile(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Profile", reflect.TypeOf((*MockIdentityUserUseCase)(nil).Profile), ctx, tenantID)
}

// RefreshToken mocks base method.
func (m *MockIdentityUserUseCase) RefreshToken(ctx context.Context, tenantID uuid.UUID, accessToken, refreshToken string) (*types.IdentityUserAuthResponse, *errors.DomainError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", ctx, tenantID, accessToken, refreshToken)
	ret0, _ := ret[0].(*types.IdentityUserAuthResponse)
	ret1, _ := ret[1].(*errors.DomainError)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockIdentityUserUseCaseMockRecorder) RefreshToken(ctx, tenantID, accessToken, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockIdentityUserUseCase)(nil).RefreshToken), ctx, tenantID, accessToken, refreshToken)
}

// Register mocks base method.
func (m *MockIdentityUserUseCase) Register(ctx context.Context, tenantID uuid.UUID, lang, email, phone string) (*types.IdentityUserAuthResponse, *errors.DomainError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, tenantID, lang, email, phone)
	ret0, _ := ret[0].(*types.IdentityUserAuthResponse)
	ret1, _ := ret[1].(*errors.DomainError)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockIdentityUserUseCaseMockRecorder) Register(ctx, tenantID, lang, email, phone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockIdentityUserUseCase)(nil).Register), ctx, tenantID, lang, email, phone)
}

// UpdateLang mocks base method.
func (m *MockIdentityUserUseCase) UpdateLang(ctx context.Context, tenantID uuid.UUID, tenantUserID, lang string) *errors.DomainError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLang", ctx, tenantID, tenantUserID, lang)
	ret0, _ := ret[0].(*errors.DomainError)
	return ret0
}

// UpdateLang indicates an expected call of UpdateLang.
func (mr *MockIdentityUserUseCaseMockRecorder) UpdateLang(ctx, tenantID, tenantUserID, lang any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLang", reflect.TypeOf((*MockIdentityUserUseCase)(nil).UpdateLang), ctx, tenantID, tenantUserID, lang)
}

// VerifyIdentifier mocks base method.
func (m *MockIdentityUserUseCase) VerifyIdentifier(ctx context.Context, tenantID uuid.UUID, flowID, code string) (*types.IdentityVerificationResponse, *errors.DomainError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyIdentifier", ctx, tenantID, flowID, code)
	ret0, _ := ret[0].(*types.IdentityVerificationResponse)
	ret1, _ := ret[1].(*errors.DomainError)
	return ret0, ret1
}

// VerifyIdentifier indicates an expected call of VerifyIdentifier.
func (mr *MockIdentityUserUseCaseMockRecorder) VerifyIdentifier(ctx, tenantID, flowID, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyIdentifier", reflect.TypeOf((*MockIdentityUserUseCase)(nil).VerifyIdentifier), ctx, tenantID, flowID, code)
}

// VerifyLogin mocks base method.
func (m *MockIdentityUserUseCase) VerifyLogin(ctx context.Context, tenantID uuid.UUID, flowID, code string) (*types.IdentityUserAuthResponse, *errors.DomainError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyLogin", ctx, tenantID, flowID, code)
	ret0, _ := ret[0].(*types.IdentityUserAuthResponse)
	ret1, _ := ret[1].(*errors.DomainError)
	return ret0, ret1
}

// VerifyLogin indicates an expected call of VerifyLogin.
func (mr *MockIdentityUserUseCaseMockRecorder) VerifyLogin(ctx, tenantID, flowID, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyLogin", reflect.TypeOf((*MockIdentityUserUseCase)(nil).VerifyLogin), ctx, tenantID, flowID, code)
}

// VerifyRegister mocks base method.
func (m *MockIdentityUserUseCase) VerifyRegister(ctx context.Context, tenantID uuid.UUID, flowID, code string) (*types.IdentityUserAuthResponse, *errors.DomainError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyRegister", ctx, tenantID, flowID, code)
	ret0, _ := ret[0].(*types.IdentityUserAuthResponse)
	ret1, _ := ret[1].(*errors.DomainError)
	return ret0, ret1
}

// VerifyRegister indicates an expected call of VerifyRegister.
func (mr *MockIdentityUserUseCaseMockRecorder) VerifyRegister(ctx, tenantID, flowID, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyRegister", reflect.TypeOf((*MockIdentityUserUseCase)(nil).VerifyRegister), ctx, tenantID, flowID, code)
}
