// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/ucases/interfaces/permission.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/ucases/interfaces/permission.go -package=mock_interfaces -destination=mocks/domain/ucases/interfaces/mock_permission.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"

	errors "github.com/lifenetwork-ai/iam-service/internal/domain/ucases/errors"
	types "github.com/lifenetwork-ai/iam-service/internal/domain/ucases/types"
	gomock "go.uber.org/mock/gomock"
)

// MockPermissionUseCase is a mock of PermissionUseCase interface.
type MockPermissionUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockPermissionUseCaseMockRecorder
	isgomock struct{}
}

// MockPermissionUseCaseMockRecorder is the mock recorder for MockPermissionUseCase.
type MockPermissionUseCaseMockRecorder struct {
	mock *MockPermissionUseCase
}

// NewMockPermissionUseCase creates a new mock instance.
func NewMockPermissionUseCase(ctrl *gomock.Controller) *MockPermissionUseCase {
	mock := &MockPermissionUseCase{ctrl: ctrl}
	mock.recorder = &MockPermissionUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermissionUseCase) EXPECT() *MockPermissionUseCaseMockRecorder {
	return m.recorder
}

// CheckPermission mocks base method.
func (m *MockPermissionUseCase) CheckPermission(ctx context.Context, request types.CheckPermissionRequest) (bool, *errors.DomainError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPermission", ctx, request)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*errors.DomainError)
	return ret0, ret1
}

// CheckPermission indicates an expected call of CheckPermission.
func (mr *MockPermissionUseCaseMockRecorder) CheckPermission(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPermission", reflect.TypeOf((*MockPermissionUseCase)(nil).CheckPermission), ctx, request)
}

// CreateRelationTuple mocks base method.
func (m *MockPermissionUseCase) CreateRelationTuple(ctx context.Context, request types.CreateRelationTupleRequest) *errors.DomainError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRelationTuple", ctx, request)
	ret0, _ := ret[0].(*errors.DomainError)
	return ret0
}

// CreateRelationTuple indicates an expected call of CreateRelationTuple.
func (mr *MockPermissionUseCaseMockRecorder) CreateRelationTuple(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRelationTuple", reflect.TypeOf((*MockPermissionUseCase)(nil).CreateRelationTuple), ctx, request)
}

// DelegateAccess mocks base method.
func (m *MockPermissionUseCase) DelegateAccess(ctx context.Context, request types.DelegateAccessRequest) (bool, *errors.DomainError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DelegateAccess", ctx, request)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*errors.DomainError)
	return ret0, ret1
}

// DelegateAccess indicates an expected call of DelegateAccess.
func (mr *MockPermissionUseCaseMockRecorder) DelegateAccess(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DelegateAccess", reflect.TypeOf((*MockPermissionUseCase)(nil).DelegateAccess), ctx, request)
}
