// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/ucases/interfaces/tenant.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/ucases/interfaces/tenant.go -package=mock_interfaces -destination=mocks/domain/ucases/interfaces/mock_tenant.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"

	domain "github.com/lifenetwork-ai/iam-service/internal/domain/entities"
	types "github.com/lifenetwork-ai/iam-service/internal/domain/types"
	errors "github.com/lifenetwork-ai/iam-service/internal/domain/ucases/errors"
	gomock "go.uber.org/mock/gomock"
)

// MockTenantUseCase is a mock of TenantUseCase interface.
type MockTenantUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockTenantUseCaseMockRecorder
	isgomock struct{}
}

// MockTenantUseCaseMockRecorder is the mock recorder for MockTenantUseCase.
type MockTenantUseCaseMockRecorder struct {
	mock *MockTenantUseCase
}

// NewMockTenantUseCase creates a new mock instance.
func NewMockTenantUseCase(ctrl *gomock.Controller) *MockTenantUseCase {
	mock := &MockTenantUseCase{ctrl: ctrl}
	mock.recorder = &MockTenantUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantUseCase) EXPECT() *MockTenantUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTenantUseCase) Create(ctx context.Context, name, publicURL, adminURL string) (*domain.Tenant, *errors.DomainError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, name, publicURL, adminURL)
	ret0, _ := ret[0].(*domain.Tenant)
	ret1, _ := ret[1].(*errors.DomainError)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTenantUseCaseMockRecorder) Create(ctx, name, publicURL, adminURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTenantUseCase)(nil).Create), ctx, name, publicURL, adminURL)
}

// Delete mocks base method.
func (m *MockTenantUseCase) Delete(ctx context.Context, id string) (*domain.Tenant, *errors.DomainError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(*domain.Tenant)
	ret1, _ := ret[1].(*errors.DomainError)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockTenantUseCaseMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTenantUseCase)(nil).Delete), ctx, id)
}

// GetAll mocks base method.
func (m *MockTenantUseCase) GetAll(ctx context.Context) ([]*domain.Tenant, *errors.DomainError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]*domain.Tenant)
	ret1, _ := ret[1].(*errors.DomainError)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockTenantUseCaseMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockTenantUseCase)(nil).GetAll), ctx)
}

// GetByID mocks base method.
func (m *MockTenantUseCase) GetByID(ctx context.Context, id string) (*domain.Tenant, *errors.DomainError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Tenant)
	ret1, _ := ret[1].(*errors.DomainError)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTenantUseCaseMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTenantUseCase)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockTenantUseCase) List(ctx context.Context, page, size int, keyword string) (*types.PaginatedResponse[domain.Tenant], *errors.DomainError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, page, size, keyword)
	ret0, _ := ret[0].(*types.PaginatedResponse[domain.Tenant])
	ret1, _ := ret[1].(*errors.DomainError)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTenantUseCaseMockRecorder) List(ctx, page, size, keyword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTenantUseCase)(nil).List), ctx, page, size, keyword)
}

// Update mocks base method.
func (m *MockTenantUseCase) Update(ctx context.Context, id, name, publicURL, adminURL string) (*domain.Tenant, *errors.DomainError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, name, publicURL, adminURL)
	ret0, _ := ret[0].(*domain.Tenant)
	ret1, _ := ret[1].(*errors.DomainError)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTenantUseCaseMockRecorder) Update(ctx, id, name, publicURL, adminURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTenantUseCase)(nil).Update), ctx, id, name, publicURL, adminURL)
}
