// Code generated by MockGen. DO NOT EDIT.
// Source: ./infrastructures/rate_limiter/fixed_window_rate_limiter.go
//
// Generated by this command:
//
//	mockgen -source=./infrastructures/rate_limiter/fixed_window_rate_limiter.go -package=mock_rate_limiter -destination=mocks/infrastructures/rate_limiter/mock_fixed_window_rate_limiter.go
//

// Package mock_rate_limiter is a generated GoMock package.
package mock_rate_limiter
