definitions:
  dto.AccountDTO:
    properties:
      api_key:
        description: Nullable
        type: string
      email:
        type: string
      id:
        type: integer
      oauth_id:
        description: Nullable
        type: string
      oauth_provider:
        description: Nullable
        type: string
      role:
        description: USER, PARTNER, CUSTOMER, VALIDATOR
        type: string
    type: object
  dto.AccountDetailDTO:
    properties:
      account:
        $ref: '#/definitions/dto.AccountDTO'
      company_name:
        type: string
      contact_name:
        type: string
      first_name:
        type: string
      id:
        type: integer
      industry:
        type: string
      last_name:
        type: string
      organization_name:
        type: string
      phone_number:
        type: string
      role:
        type: string
      validation_organization:
        type: string
    type: object
  dto.LoginPayloadDTO:
    properties:
      email:
        description: User email
        type: string
      password:
        description: User password
        type: string
    required:
    - email
    - password
    type: object
  dto.LogoutPayloadDTO:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  dto.RefreshTokenPayloadDTO:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  dto.RegisterPayloadDTO:
    properties:
      company_name:
        type: string
      contact_name:
        type: string
      email:
        type: string
      first_name:
        type: string
      industry:
        type: string
      last_name:
        type: string
      organization_name:
        type: string
      password:
        type: string
      phone_number:
        type: string
      role:
        description: USER, PARTNER, CUSTOMER, VALIDATOR
        type: string
      validation_organization:
        type: string
    required:
    - email
    - password
    - role
    type: object
  dto.TokenPairDTO:
    properties:
      access_token:
        description: The JWT Access Token
        type: string
      refresh_token:
        description: The plain Refresh Token
        type: string
    type: object
  response.GeneralError:
    properties:
      code:
        type: integer
      errors:
        items:
          type: string
        type: array
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/account/me:
    get:
      consumes:
      - application/json
      description: This endpoint retrieves the details of the currently authenticated
        user using the provided access token.
      parameters:
      - description: Bearer access token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: User details
          schema:
            $ref: '#/definitions/dto.AccountDetailDTO'
        "401":
          description: Invalid or expired token
          schema:
            $ref: '#/definitions/response.GeneralError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.GeneralError'
      summary: Get current user details
      tags:
      - account
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      description: This endpoint authenticates the user by email and password, and
        returns an access token and refresh token.
      parameters:
      - description: User credentials (email and password)
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/dto.LoginPayloadDTO'
      produces:
      - application/json
      responses:
        "200":
          description: 'Login successful: {\"access_token\": \"...\", \"refresh_token\":
            \"...\"}'
          schema:
            $ref: '#/definitions/dto.TokenPairDTO'
        "400":
          description: Invalid payload
          schema:
            $ref: '#/definitions/response.GeneralError'
        "401":
          description: Invalid credentials
          schema:
            $ref: '#/definitions/response.GeneralError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.GeneralError'
      summary: Authenticate user
      tags:
      - authentication
  /api/v1/auth/logout:
    post:
      consumes:
      - application/json
      description: This endpoint invalidates the refresh token, effectively logging
        the user out.
      parameters:
      - description: Logout payload containing the refresh token
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/dto.LogoutPayloadDTO'
      produces:
      - application/json
      responses:
        "200":
          description: 'Logout successful: {\"success\": true}'
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid payload
          schema:
            $ref: '#/definitions/response.GeneralError'
        "401":
          description: Invalid or expired refresh token
          schema:
            $ref: '#/definitions/response.GeneralError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.GeneralError'
      summary: Logout user
      tags:
      - authentication
  /api/v1/auth/refresh-tokens:
    post:
      consumes:
      - application/json
      description: This endpoint generates a new pair of access and refresh tokens
        using a valid refresh token.
      parameters:
      - description: Refresh token payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/dto.RefreshTokenPayloadDTO'
      produces:
      - application/json
      responses:
        "200":
          description: Tokens refreshed successfully
          schema:
            $ref: '#/definitions/dto.TokenPairDTO'
        "400":
          description: Invalid payload
          schema:
            $ref: '#/definitions/response.GeneralError'
        "401":
          description: Invalid or expired refresh token
          schema:
            $ref: '#/definitions/response.GeneralError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.GeneralError'
      summary: Refresh tokens
      tags:
      - authentication
  /api/v1/auth/register:
    post:
      consumes:
      - application/json
      description: This endpoint registers a new account and its associated role-specific
        details.
      parameters:
      - description: User registration details
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterPayloadDTO'
      produces:
      - application/json
      responses:
        "201":
          description: 'Registration successful: {\"success\": true}'
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid payload
          schema:
            $ref: '#/definitions/response.GeneralError'
        "409":
          description: Account already exists
          schema:
            $ref: '#/definitions/response.GeneralError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.GeneralError'
      summary: Register a new account
      tags:
      - authentication
  /api/v1/auth/validate-token:
    get:
      consumes:
      - application/json
      description: This endpoint validates an access token and retrieves the corresponding
        user's details.
      parameters:
      - description: Bearer access token (e.g., 'Bearer <token>')
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'Token is valid: User details'
          schema:
            $ref: '#/definitions/dto.AccountDTO'
        "401":
          description: Invalid or expired token
          schema:
            $ref: '#/definitions/response.GeneralError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.GeneralError'
      summary: Validate access token
      tags:
      - authentication
swagger: "2.0"
