definitions:
  constants.IdentifierType:
    enum:
    - email
    - username
    - phone
    type: string
    x-enum-varnames:
    - IdentifierEmail
    - IdentifierUsername
    - IdentifierPhone
  dto.AccountDTO:
    properties:
      api_key:
        description: Nullable
        type: string
      email:
        type: string
      id:
        type: string
      oauth_id:
        description: Nullable
        type: string
      oauth_provider:
        description: Nullable
        type: string
      private_key:
        description: Nullable
        type: string
      public_key:
        description: Nullable
        type: string
      role:
        description: USER, PARTNER, CUSTOMER, VALIDATOR
        type: string
      username:
        type: string
    type: object
  dto.AccountDetailDTO:
    properties:
      account:
        $ref: '#/definitions/dto.AccountDTO'
      company_name:
        type: string
      contact_name:
        type: string
      first_name:
        type: string
      id:
        type: string
      industry:
        type: string
      last_name:
        type: string
      organization_name:
        type: string
      phone_number:
        type: string
      validation_organization:
        type: string
    type: object
  dto.DataAccessRequestDTO:
    properties:
      created_at:
        description: Timestamp of when the request was created
        type: string
      id:
        description: Unique ID of the request
        type: string
      reason_for_rejection:
        description: Optional reason for rejection
        type: string
      reason_for_request:
        description: Reason for the request
        type: string
      request_account_id:
        description: ID of the account being accessed
        type: string
      requester_account_id:
        description: ID of the account making the request
        type: string
      requester_role:
        description: Role of the requester
        type: string
      status:
        description: Status of the request (PENDING, APPROVED, REJECTED)
        type: string
      updated_at:
        description: Timestamp of when the request was last updated
        type: string
    type: object
  dto.DataAccessRequestPayloadDTO:
    properties:
      file_id:
        description: File ID
        type: string
      reason_for_request:
        description: Reason for the data access request
        type: string
      request_account_id:
        description: Account whose data is being requested
        type: string
    required:
    - file_id
    - reason_for_request
    - request_account_id
    type: object
  dto.LoginPayloadDTO:
    properties:
      identifier:
        description: Identifier (email, username, or phone number)
        type: string
      identifier_type:
        allOf:
        - $ref: '#/definitions/constants.IdentifierType'
        description: 'Type of identifier: "email", "username", or "phone"'
      password:
        description: User password
        type: string
    required:
    - identifier
    - identifier_type
    - password
    type: object
  dto.LogoutPayloadDTO:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  dto.RefreshTokenPayloadDTO:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  dto.RegisterPayloadDTO:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  dto.RoleDetailsPayloadDTO:
    properties:
      company_name:
        description: Partner fields
        type: string
      contact_name:
        type: string
      first_name:
        description: Common fields
        type: string
      industry:
        type: string
      last_name:
        type: string
      organization_name:
        description: Customer fields
        type: string
      phone_number:
        type: string
      validation_organization:
        description: Validator fields
        type: string
    type: object
  dto.TokenPairDTO:
    properties:
      access_token:
        description: The JWT Access Token
        type: string
      refresh_token:
        description: The plain Refresh Token
        type: string
    type: object
  dto.UpdateRolePayloadDTO:
    properties:
      role:
        description: USER, PARTNER, CUSTOMER, VALIDATOR
        type: string
      role_details:
        allOf:
        - $ref: '#/definitions/dto.RoleDetailsPayloadDTO'
        description: Role-specific details
    required:
    - role
    type: object
  response.GeneralError:
    properties:
      code:
        type: integer
      errors:
        items:
          type: string
        type: array
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/account/me:
    get:
      consumes:
      - application/json
      description: This endpoint retrieves the details of the currently authenticated
        user using the provided access token.
      parameters:
      - description: Bearer access token (e.g., 'Bearer <token>')
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: User details
          schema:
            $ref: '#/definitions/dto.AccountDetailDTO'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.GeneralError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/response.GeneralError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.GeneralError'
      summary: Get current user details
      tags:
      - account
  /api/v1/account/role:
    put:
      consumes:
      - application/json
      description: Update the role of an account and save associated role-specific
        details.
      parameters:
      - description: Bearer access token (e.g., 'Bearer <token>')
        in: header
        name: Authorization
        required: true
        type: string
      - description: Payload containing role and role-specific details
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateRolePayloadDTO'
      produces:
      - application/json
      responses:
        "200":
          description: Account role updated successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid payload
          schema:
            $ref: '#/definitions/response.GeneralError'
        "404":
          description: Account not found
          schema:
            $ref: '#/definitions/response.GeneralError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.GeneralError'
      summary: Update account role and role-specific details
      tags:
      - account
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      description: This endpoint authenticates the user by email, username, or phone
        number, and returns an access token and refresh token.
      parameters:
      - description: 'User credentials (identifier, password, and identifier_type
          (e.g: email, username, phone))'
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/dto.LoginPayloadDTO'
      produces:
      - application/json
      responses:
        "200":
          description: 'Login successful: {\"access_token\": \"...\", \"refresh_token\":
            \"...\"}'
          schema:
            $ref: '#/definitions/dto.TokenPairDTO'
        "400":
          description: Invalid payload
          schema:
            $ref: '#/definitions/response.GeneralError'
        "401":
          description: Invalid credentials
          schema:
            $ref: '#/definitions/response.GeneralError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.GeneralError'
      summary: Authenticate user
      tags:
      - authentication
  /api/v1/auth/logout:
    post:
      consumes:
      - application/json
      description: This endpoint invalidates the refresh token, effectively logging
        the user out.
      parameters:
      - description: Logout payload containing the refresh token
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/dto.LogoutPayloadDTO'
      produces:
      - application/json
      responses:
        "200":
          description: 'Logout successful: {\"success\": true}'
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid payload
          schema:
            $ref: '#/definitions/response.GeneralError'
        "401":
          description: Invalid or expired refresh token
          schema:
            $ref: '#/definitions/response.GeneralError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.GeneralError'
      summary: Logout user
      tags:
      - authentication
  /api/v1/auth/refresh-tokens:
    post:
      consumes:
      - application/json
      description: This endpoint generates a new pair of access and refresh tokens
        using a valid refresh token.
      parameters:
      - description: Refresh token payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/dto.RefreshTokenPayloadDTO'
      produces:
      - application/json
      responses:
        "200":
          description: Tokens refreshed successfully
          schema:
            $ref: '#/definitions/dto.TokenPairDTO'
        "400":
          description: Invalid payload
          schema:
            $ref: '#/definitions/response.GeneralError'
        "401":
          description: Invalid or expired refresh token
          schema:
            $ref: '#/definitions/response.GeneralError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.GeneralError'
      summary: Refresh tokens
      tags:
      - authentication
  /api/v1/auth/register:
    post:
      consumes:
      - application/json
      description: This endpoint registers a new account and its associated role-specific
        details.
      parameters:
      - description: User registration details
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterPayloadDTO'
      produces:
      - application/json
      responses:
        "201":
          description: 'Registration successful: {\"success\": true}'
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid payload
          schema:
            $ref: '#/definitions/response.GeneralError'
        "409":
          description: Account already exists
          schema:
            $ref: '#/definitions/response.GeneralError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.GeneralError'
      summary: Register a new account
      tags:
      - authentication
  /api/v1/data-access:
    post:
      consumes:
      - application/json
      description: Allows a requester to create a new data access request for a specific
        user.
      parameters:
      - description: Bearer access token (e.g., 'Bearer <token>')
        in: header
        name: Authorization
        required: true
        type: string
      - description: Payload containing user ID and reason for request
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/dto.DataAccessRequestPayloadDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Data access request created successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid payload
          schema:
            $ref: '#/definitions/response.GeneralError'
        "404":
          description: Requested user not found
          schema:
            $ref: '#/definitions/response.GeneralError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.GeneralError'
      summary: Create a data access request
      tags:
      - data-access
  /api/v1/data-access/{requesterAccountID}/approve:
    put:
      consumes:
      - application/json
      description: Approves a pending data access request for the authenticated user.
      parameters:
      - description: Bearer access token (e.g., 'Bearer <token>')
        in: header
        name: Authorization
        required: true
        type: string
      - description: ID of the account making the request
        in: path
        name: requesterAccountID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Request approved successfully
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.GeneralError'
        "404":
          description: Request not found
          schema:
            $ref: '#/definitions/response.GeneralError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.GeneralError'
      summary: Approve a data access request
      tags:
      - data-access
  /api/v1/data-access/{requesterAccountID}/reject:
    put:
      consumes:
      - application/json
      description: Rejects a pending data access request for the authenticated user.
      parameters:
      - description: Bearer access token (e.g., 'Bearer <token>')
        in: header
        name: Authorization
        required: true
        type: string
      - description: ID of the account making the request
        in: path
        name: requesterAccountID
        required: true
        type: string
      - description: Payload containing the reason for rejection
        in: body
        name: payload
        required: true
        schema:
          additionalProperties:
            type: string
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: Request rejected successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid payload
          schema:
            $ref: '#/definitions/response.GeneralError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.GeneralError'
        "404":
          description: Request not found
          schema:
            $ref: '#/definitions/response.GeneralError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.GeneralError'
      summary: Reject a data access request
      tags:
      - data-access
  /api/v1/data-access/pending:
    get:
      consumes:
      - application/json
      description: Fetches a list of pending data access requests for the authenticated
        user.
      parameters:
      - description: Bearer access token (e.g., 'Bearer <token>')
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: List of pending data access requests
          schema:
            items:
              $ref: '#/definitions/dto.DataAccessRequestDTO'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.GeneralError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.GeneralError'
      summary: Get pending data access requests
      tags:
      - data-access
  /api/v1/validators/active:
    get:
      consumes:
      - application/json
      description: Fetches a list of active validators.
      parameters:
      - description: Bearer access token (e.g., 'Bearer <token>')
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: List of active validators
          schema:
            items:
              $ref: '#/definitions/dto.AccountDetailDTO'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.GeneralError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/response.GeneralError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.GeneralError'
      summary: Get Active Validators
      tags:
      - validators
swagger: "2.0"
