definitions:
  dto.LoginPayloadDTO:
    properties:
      email:
        description: User email
        type: string
      password:
        description: User password
        type: string
    required:
    - email
    - password
    type: object
  dto.TokenPairDTO:
    properties:
      access_token:
        description: The JWT Access Token
        type: string
      refresh_token:
        description: The plain Refresh Token
        type: string
    type: object
  response.GeneralError:
    properties:
      code:
        type: integer
      errors:
        items:
          type: string
        type: array
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      description: This endpoint authenticates the user by email and password, and
        returns an access token and refresh token.
      parameters:
      - description: User credentials (email and password)
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/dto.LoginPayloadDTO'
      produces:
      - application/json
      responses:
        "200":
          description: 'Login successful: {\"access_token\": \"...\", \"refresh_token\":
            \"...\"}'
          schema:
            $ref: '#/definitions/dto.TokenPairDTO'
        "400":
          description: Invalid payload
          schema:
            $ref: '#/definitions/response.GeneralError'
        "401":
          description: Invalid credentials
          schema:
            $ref: '#/definitions/response.GeneralError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.GeneralError'
      summary: Authenticate user
      tags:
      - authentication
swagger: "2.0"
